[[headers]]
# .jpg 파일에 대한 경로 지정
for = "/*.jpg"
[headers.values]
Cache-Control = "max-age=2592000"

[[headers]]
# .png 파일에 대한 경로 지정
for = "/*.png"
[headers.values]
Cache-Control = "max-age=2592000"

[[headers]]
# .webp 파일에 대한 경로 지정
for = "/*.webp"
[headers.values]
Cache-Control = "max-age=2592000"
