/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/Animation_real/animation_real.glb -o src/components/Animation_real.jsx -r public -k 
*/

import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import React, { useRef } from "react";
import { useExplode } from "../../hooks/useExplode";

export function AnimationReal(props) {
  const { nodes, materials } = useGLTF("/Animation_real/animation_real.glb");
  const group = useRef();
  const { stonedistance } = useControls({
    stonedistance: {
      value: 10,
      min: 0,
      max: 50,
    },
  });
  useExplode(group, {
    distance: stonedistance,
    rotationEnabled: true,
  });
  return (
    <group {...props} dispose={null} ref={group}>
      {/* <PerspectiveCamera
        name="Camera"
        makeDefault={false}
        far={100}
        near={0.1}
        fov={22.895}
        position={[7.359, 4.958, 6.926]}
        rotation={[-0.627, 0.71, 0.441]}
      /> */}
      <pointLight
        name="Point"
        decay={2}
        color="#a9e5ff"
        position={[-0.196, 3.056, -0.085]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <mesh
        name="Sphere_cell001"
        geometry={nodes.Sphere_cell001.geometry}
        material={nodes.Sphere_cell001.material}
        position={[0.649, 4.05, 0.305]}
      />
      <mesh
        name="Sphere_cell002"
        geometry={nodes.Sphere_cell002.geometry}
        material={nodes.Sphere_cell002.material}
        position={[0.076, 2.479, -0.139]}
      />
      <mesh
        name="Sphere_cell003"
        geometry={nodes.Sphere_cell003.geometry}
        material={nodes.Sphere_cell003.material}
        position={[0.416, 2.802, -0.577]}
      />
      <mesh
        name="Sphere_cell004"
        geometry={nodes.Sphere_cell004.geometry}
        material={nodes.Sphere_cell004.material}
        position={[-0.169, 3.716, -0.416]}
      />
      <mesh
        name="Sphere_cell005"
        geometry={nodes.Sphere_cell005.geometry}
        material={nodes.Sphere_cell005.material}
        position={[-0.987, 3.875, -0.209]}
      />
      <mesh
        name="Sphere_cell006"
        geometry={nodes.Sphere_cell006.geometry}
        material={nodes.Sphere_cell006.material}
        position={[-0.022, 3.519, -0.981]}
      />
      <mesh
        name="Sphere_cell008"
        geometry={nodes.Sphere_cell008.geometry}
        material={nodes.Sphere_cell008.material}
        position={[-0.489, 3.756, 0.185]}
      />
      <mesh
        name="Sphere_cell009"
        geometry={nodes.Sphere_cell009.geometry}
        material={nodes.Sphere_cell009.material}
        position={[-0.102, 4.467, -0.023]}
      />
      <mesh
        name="Sphere_cell010"
        geometry={nodes.Sphere_cell010.geometry}
        material={nodes.Sphere_cell010.material}
        position={[-0.488, 3.513, 0.928]}
      />
      <mesh
        name="Sphere_cell011"
        geometry={nodes.Sphere_cell011.geometry}
        material={nodes.Sphere_cell011.material}
        position={[-0.548, 4.39, 0.018]}
      />
      <mesh
        name="Sphere_cell012"
        geometry={nodes.Sphere_cell012.geometry}
        material={nodes.Sphere_cell012.material}
        position={[-0.855, 3.446, 0.436]}
      />
      <mesh
        name="Sphere_cell014"
        geometry={nodes.Sphere_cell014.geometry}
        material={nodes.Sphere_cell014.material}
        position={[-0.359, 2.44, 0.058]}
      />
      <mesh
        name="Sphere_cell015"
        geometry={nodes.Sphere_cell015.geometry}
        material={nodes.Sphere_cell015.material}
        position={[0.005, 4.159, -0.567]}
      />
      <mesh
        name="Sphere_cell016"
        geometry={nodes.Sphere_cell016.geometry}
        material={nodes.Sphere_cell016.material}
        position={[-0.264, 4.171, -0.39]}
      />
      <mesh
        name="Sphere_cell017"
        geometry={nodes.Sphere_cell017.geometry}
        material={nodes.Sphere_cell017.material}
        position={[-0.252, 3.314, -0.815]}
      />
      <mesh
        name="Sphere_cell018"
        geometry={nodes.Sphere_cell018.geometry}
        material={nodes.Sphere_cell018.material}
        position={[-0.012, 4.257, 0.402]}
      />
      <mesh
        name="Sphere_cell019"
        geometry={nodes.Sphere_cell019.geometry}
        material={nodes.Sphere_cell019.material}
        position={[-0.326, 2.786, -0.629]}
      />
      <mesh
        name="Sphere_cell020"
        geometry={nodes.Sphere_cell020.geometry}
        material={nodes.Sphere_cell020.material}
        position={[-1.028, 3.134, 0.298]}
      />
      <mesh
        name="Sphere_cell021"
        geometry={nodes.Sphere_cell021.geometry}
        material={nodes.Sphere_cell021.material}
        position={[-0.022, 2.88, 0.68]}
      />
      <mesh
        name="Sphere_cell022"
        geometry={nodes.Sphere_cell022.geometry}
        material={nodes.Sphere_cell022.material}
        position={[-0.551, 2.618, -0.179]}
      />
      <mesh
        name="Sphere_cell024"
        geometry={nodes.Sphere_cell024.geometry}
        material={nodes.Sphere_cell024.material}
        position={[-0.675, 4.04, 0.564]}
      />
      <mesh
        name="Sphere_cell025"
        geometry={nodes.Sphere_cell025.geometry}
        material={nodes.Sphere_cell025.material}
        position={[0.021, 3.071, -0.827]}
      />
      <mesh
        name="Sphere_cell026"
        geometry={nodes.Sphere_cell026.geometry}
        material={nodes.Sphere_cell026.material}
        position={[-0.41, 3.923, 0.711]}
      />
      <mesh
        name="Sphere_cell028"
        geometry={nodes.Sphere_cell028.geometry}
        material={nodes.Sphere_cell028.material}
        position={[0.617, 3.748, -0.547]}
      />
      <mesh
        name="Sphere_cell029"
        geometry={nodes.Sphere_cell029.geometry}
        material={nodes.Sphere_cell029.material}
        position={[0.047, 2.668, -0.539]}
      />
      <mesh
        name="Sphere_cell030"
        geometry={nodes.Sphere_cell030.geometry}
        material={nodes.Sphere_cell030.material}
        position={[-0.073, 3.965, -0.813]}
      />
      <mesh
        name="Sphere_cell031"
        geometry={nodes.Sphere_cell031.geometry}
        material={nodes.Sphere_cell031.material}
        position={[-0.758, 3.718, 0.706]}
      />
      <mesh
        name="Sphere_cell033"
        geometry={nodes.Sphere_cell033.geometry}
        material={nodes.Sphere_cell033.material}
        position={[0.777, 3.792, 0.301]}
      />
      <mesh
        name="Sphere_cell034"
        geometry={nodes.Sphere_cell034.geometry}
        material={nodes.Sphere_cell034.material}
        position={[0.678, 3.302, -0.352]}
      />
      <mesh
        name="Sphere_cell035"
        geometry={nodes.Sphere_cell035.geometry}
        material={nodes.Sphere_cell035.material}
        position={[-0.283, 2.51, 0.363]}
      />
      <mesh
        name="Sphere_cell036"
        geometry={nodes.Sphere_cell036.geometry}
        material={nodes.Sphere_cell036.material}
        position={[0.08, 3.837, 0.85]}
      />
      <mesh
        name="Sphere_cell037"
        geometry={nodes.Sphere_cell037.geometry}
        material={nodes.Sphere_cell037.material}
        position={[0.641, 3.466, 0.5]}
      />
      <mesh
        name="Sphere_cell038"
        geometry={nodes.Sphere_cell038.geometry}
        material={nodes.Sphere_cell038.material}
        position={[-0.46, 2.675, 0.247]}
      />
      <mesh
        name="Sphere_cell039"
        geometry={nodes.Sphere_cell039.geometry}
        material={nodes.Sphere_cell039.material}
        position={[-0.88, 4.081, -0.059]}
      />
      <mesh
        name="Sphere_cell040"
        geometry={nodes.Sphere_cell040.geometry}
        material={nodes.Sphere_cell040.material}
        position={[0.402, 2.661, 0.35]}
      />
      <mesh
        name="Sphere_cell041"
        geometry={nodes.Sphere_cell041.geometry}
        material={nodes.Sphere_cell041.material}
        position={[-0.339, 3.672, -0.796]}
      />
      <mesh
        name="Sphere_cell042"
        geometry={nodes.Sphere_cell042.geometry}
        material={nodes.Sphere_cell042.material}
        position={[0.187, 3.19, 0.899]}
      />
      <mesh
        name="Sphere_cell043"
        geometry={nodes.Sphere_cell043.geometry}
        material={nodes.Sphere_cell043.material}
        position={[-0.324, 3.851, -0.853]}
      />
      <mesh
        name="Sphere_cell046"
        geometry={nodes.Sphere_cell046.geometry}
        material={nodes.Sphere_cell046.material}
        position={[-0.991, 3.759, 0.232]}
      />
      <mesh
        name="Sphere_cell047"
        geometry={nodes.Sphere_cell047.geometry}
        material={nodes.Sphere_cell047.material}
        position={[-0.244, 4.134, 0.75]}
      />
      <mesh
        name="Sphere_cell048"
        geometry={nodes.Sphere_cell048.geometry}
        material={nodes.Sphere_cell048.material}
        position={[-0.296, 4.43, 0.102]}
      />
      <mesh
        name="Sphere_cell049"
        geometry={nodes.Sphere_cell049.geometry}
        material={nodes.Sphere_cell049.material}
        position={[0.24, 3.903, -0.116]}
      />
      <mesh
        name="Sphere_cell050"
        geometry={nodes.Sphere_cell050.geometry}
        material={nodes.Sphere_cell050.material}
        position={[-0.591, 4.238, 0.183]}
      />
      <mesh
        name="Sphere_cell051"
        geometry={nodes.Sphere_cell051.geometry}
        material={nodes.Sphere_cell051.material}
        position={[-1.123, 3.46, -0.048]}
      />
      <mesh
        name="Sphere_cell052"
        geometry={nodes.Sphere_cell052.geometry}
        material={nodes.Sphere_cell052.material}
        position={[0.361, 4.259, -0.268]}
      />
      <mesh
        name="Sphere_cell053"
        geometry={nodes.Sphere_cell053.geometry}
        material={nodes.Sphere_cell053.material}
        position={[0.165, 2.66, 0.565]}
      />
      <mesh
        name="Sphere_cell054"
        geometry={nodes.Sphere_cell054.geometry}
        material={nodes.Sphere_cell054.material}
        position={[-0.961, 2.956, -0.088]}
      />
      <mesh
        name="Sphere_cell055"
        geometry={nodes.Sphere_cell055.geometry}
        material={nodes.Sphere_cell055.material}
        position={[0.56, 2.659, -0.123]}
      />
      <mesh
        name="Sphere_cell056"
        geometry={nodes.Sphere_cell056.geometry}
        material={nodes.Sphere_cell056.material}
        position={[-0.642, 3.021, -0.692]}
      />
      <mesh
        name="Sphere_cell057"
        geometry={nodes.Sphere_cell057.geometry}
        material={nodes.Sphere_cell057.material}
        position={[-0.837, 3.528, -0.73]}
      />
      <mesh
        name="Sphere_cell058"
        geometry={nodes.Sphere_cell058.geometry}
        material={nodes.Sphere_cell058.material}
        position={[-1.021, 3.164, -0.446]}
      />
      <mesh
        name="Sphere_cell059"
        geometry={nodes.Sphere_cell059.geometry}
        material={nodes.Sphere_cell059.material}
        position={[0.57, 2.845, -0.133]}
      />
      <mesh
        name="Sphere_cell060"
        geometry={nodes.Sphere_cell060.geometry}
        material={nodes.Sphere_cell060.material}
        position={[0.139, 2.489, 0.176]}
      />
      <mesh
        name="Sphere_cell061"
        geometry={nodes.Sphere_cell061.geometry}
        material={nodes.Sphere_cell061.material}
        position={[-0.518, 2.648, 0.543]}
      />
      <mesh
        name="Sphere_cell063"
        geometry={nodes.Sphere_cell063.geometry}
        material={nodes.Sphere_cell063.material}
        position={[0.277, 4.097, -0.565]}
      />
      <mesh
        name="Sphere_cell064"
        geometry={nodes.Sphere_cell064.geometry}
        material={nodes.Sphere_cell064.material}
        position={[-0.285, 2.474, -0.289]}
      />
      <mesh
        name="Sphere_cell066"
        geometry={nodes.Sphere_cell066.geometry}
        material={nodes.Sphere_cell066.material}
        position={[-0.271, 3.077, 0.983]}
      />
      <mesh
        name="Sphere_cell067"
        geometry={nodes.Sphere_cell067.geometry}
        material={nodes.Sphere_cell067.material}
        position={[-0.484, 4.304, -0.31]}
      />
      <mesh
        name="Sphere_cell068"
        geometry={nodes.Sphere_cell068.geometry}
        material={nodes.Sphere_cell068.material}
        position={[0.341, 3.626, -0.38]}
      />
      <mesh
        name="Sphere_cell069"
        geometry={nodes.Sphere_cell069.geometry}
        material={nodes.Sphere_cell069.material}
        position={[0.398, 4.197, 0.063]}
      />
      <mesh
        name="Sphere_cell070"
        geometry={nodes.Sphere_cell070.geometry}
        material={nodes.Sphere_cell070.material}
        position={[0.042, 3.017, -0.105]}
      />
      <mesh
        name="Sphere_cell071"
        geometry={nodes.Sphere_cell071.geometry}
        material={nodes.Sphere_cell071.material}
        position={[-0.91, 2.992, -0.477]}
      />
      <mesh
        name="Sphere_cell072"
        geometry={nodes.Sphere_cell072.geometry}
        material={nodes.Sphere_cell072.material}
        position={[-0.758, 2.753, -0.412]}
      />
      <mesh
        name="Sphere_cell073"
        geometry={nodes.Sphere_cell073.geometry}
        material={nodes.Sphere_cell073.material}
        position={[-0.541, 3.431, -0.884]}
      />
      <mesh
        name="Sphere_cell074"
        geometry={nodes.Sphere_cell074.geometry}
        material={nodes.Sphere_cell074.material}
        position={[-0.984, 3.481, -0.315]}
      />
      <mesh
        name="Sphere_cell076"
        geometry={nodes.Sphere_cell076.geometry}
        material={nodes.Sphere_cell076.material}
        position={[-0.892, 3.256, -0.606]}
      />
      <mesh
        name="Sphere_cell077"
        geometry={nodes.Sphere_cell077.geometry}
        material={nodes.Sphere_cell077.material}
        position={[-0.73, 3.252, 0.763]}
      />
      <mesh
        name="Sphere_cell078"
        geometry={nodes.Sphere_cell078.geometry}
        material={nodes.Sphere_cell078.material}
        position={[-0.027, 4.411, -0.216]}
      />
      <mesh
        name="Sphere_cell079"
        geometry={nodes.Sphere_cell079.geometry}
        material={nodes.Sphere_cell079.material}
        position={[-0.725, 3.801, -0.55]}
      />
      <mesh
        name="Sphere_cell080"
        geometry={nodes.Sphere_cell080.geometry}
        material={nodes.Sphere_cell080.material}
        position={[-0.185, 3.385, 0.894]}
      />
      <mesh
        name="Sphere_cell081"
        geometry={nodes.Sphere_cell081.geometry}
        material={nodes.Sphere_cell081.material}
        position={[0.062, 3.576, 0.311]}
      />
      <mesh
        name="Sphere_cell082"
        geometry={nodes.Sphere_cell082.geometry}
        material={nodes.Sphere_cell082.material}
        position={[-0.74, 4.156, 0.402]}
      />
      <mesh
        name="Sphere_cell083"
        geometry={nodes.Sphere_cell083.geometry}
        material={nodes.Sphere_cell083.material}
        position={[0.322, 3.481, -0.793]}
      />
      <mesh
        name="Sphere_cell084"
        geometry={nodes.Sphere_cell084.geometry}
        material={nodes.Sphere_cell084.material}
        position={[-0.42, 4.29, 0.538]}
      />
      <mesh
        name="Sphere_cell086"
        geometry={nodes.Sphere_cell086.geometry}
        material={nodes.Sphere_cell086.material}
        position={[0.483, 3.033, 0.477]}
      />
      <mesh
        name="Sphere_cell088"
        geometry={nodes.Sphere_cell088.geometry}
        material={nodes.Sphere_cell088.material}
        position={[0.573, 3.994, 0.482]}
      />
      <mesh
        name="Sphere_cell089"
        geometry={nodes.Sphere_cell089.geometry}
        material={nodes.Sphere_cell089.material}
        position={[0.596, 3.437, -0.732]}
      />
      <mesh
        name="Sphere_cell090"
        geometry={nodes.Sphere_cell090.geometry}
        material={nodes.Sphere_cell090.material}
        position={[0.411, 3.682, 0.765]}
      />
      <mesh
        name="Sphere_cell091"
        geometry={nodes.Sphere_cell091.geometry}
        material={nodes.Sphere_cell091.material}
        position={[-0.777, 3.971, 0.189]}
      />
      <mesh
        name="Sphere_cell092"
        geometry={nodes.Sphere_cell092.geometry}
        material={nodes.Sphere_cell092.material}
        position={[-0.38, 2.957, 0.738]}
      />
      <mesh
        name="Sphere_cell093"
        geometry={nodes.Sphere_cell093.geometry}
        material={nodes.Sphere_cell093.material}
        position={[0.71, 3.868, -0.291]}
      />
      <mesh
        name="Sphere_cell094"
        geometry={nodes.Sphere_cell094.geometry}
        material={nodes.Sphere_cell094.material}
        position={[-0.631, 3.212, -0.098]}
      />
      <mesh
        name="Sphere_cell096"
        geometry={nodes.Sphere_cell096.geometry}
        material={nodes.Sphere_cell096.material}
        position={[-0.706, 2.851, 0.528]}
      />
      <mesh
        name="Sphere_cell097"
        geometry={nodes.Sphere_cell097.geometry}
        material={nodes.Sphere_cell097.material}
        position={[0.75, 3.705, 0.069]}
      />
      <mesh
        name="Cube"
        geometry={nodes.Cube.geometry}
        material={materials["Material.002"]}
        position={[-0.194, 3.44, -0.047]}
        scale={10.13}
      />
    </group>
  );
}

useGLTF.preload("/Animation_real/animation_real.glb");
