/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/Lava/lava.glb -o src/component/canvas/Lava.jsx -r public -k 
*/

import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import React, { useRef } from "react";
import { useExplode } from "../hooks/useExplode";

export function Lava(props) {
  const { nodes, materials } = useGLTF("/Lava/lava.glb");
  const group = useRef();
  const { bluebirddistance } = useControls({
    bluebirddistance: {
      value: 2.4,
      min: 0,
      max: 10,
    },
  });
  useExplode(group, {
    distance: bluebirddistance,
    rotationEnabled: true,
  });
  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="origin"
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Sphere_cell001"
        geometry={nodes.Sphere_cell001.geometry}
        material={materials["Material.001"]}
        position={[-0.66, -0.194, -0.669]}
      />
      <mesh
        name="Sphere_cell003"
        geometry={nodes.Sphere_cell003.geometry}
        material={materials["Material.001"]}
        position={[-0.228, -0.609, -0.657]}
      />
      <mesh
        name="Sphere_cell004"
        geometry={nodes.Sphere_cell004.geometry}
        material={materials["Material.001"]}
        position={[-0.164, -0.906, -0.301]}
      />
      <mesh
        name="Sphere_cell005"
        geometry={nodes.Sphere_cell005.geometry}
        material={materials["Material.001"]}
        position={[-0.189, -0.955, -0.034]}
      />
      <mesh
        name="Sphere_cell006"
        geometry={nodes.Sphere_cell006.geometry}
        material={materials["Material.001"]}
        position={[-0.22, -0.795, 0.432]}
      />
      <mesh
        name="Sphere_cell007"
        geometry={nodes.Sphere_cell007.geometry}
        material={materials["Material.001"]}
        position={[0.68, 0.414, 0.122]}
      />
      <mesh
        name="Sphere_cell008"
        geometry={nodes.Sphere_cell008.geometry}
        material={materials["Material.001"]}
        position={[-0.742, 0.434, -0.364]}
      />
      <mesh
        name="Sphere_cell009"
        geometry={nodes.Sphere_cell009.geometry}
        material={materials["Material.001"]}
        position={[0.319, 0.557, -0.757]}
      />
      <mesh
        name="Sphere_cell011"
        geometry={nodes.Sphere_cell011.geometry}
        material={materials["Material.001"]}
        position={[0.215, 0.45, 0.005]}
      />
      <mesh
        name="Sphere_cell012"
        geometry={nodes.Sphere_cell012.geometry}
        material={materials["Material.001"]}
        position={[-0.144, 0.835, 0.4]}
      />
      <mesh
        name="Sphere_cell013"
        geometry={nodes.Sphere_cell013.geometry}
        material={materials["Material.001"]}
        position={[0.551, -0.396, 0.611]}
      />
      <mesh
        name="Sphere_cell014"
        geometry={nodes.Sphere_cell014.geometry}
        material={materials["Material.001"]}
        position={[-0.824, 0.168, -0.057]}
      />
      <mesh
        name="Sphere_cell015"
        geometry={nodes.Sphere_cell015.geometry}
        material={materials["Material.001"]}
        position={[-0.5, -0.613, 0.493]}
      />
      <mesh
        name="Sphere_cell016"
        geometry={nodes.Sphere_cell016.geometry}
        material={materials["Material.001"]}
        position={[-0.635, 0.55, 0.046]}
      />
      <mesh
        name="Sphere_cell017"
        geometry={nodes.Sphere_cell017.geometry}
        material={materials["Material.001"]}
        position={[0.895, 0.361, -0.109]}
      />
      <mesh
        name="Sphere_cell018"
        geometry={nodes.Sphere_cell018.geometry}
        material={materials["Material.001"]}
        position={[-0.033, 0.862, -0.22]}
      />
      <mesh
        name="Sphere_cell019"
        geometry={nodes.Sphere_cell019.geometry}
        material={materials["Material.001"]}
        position={[0.805, 0.397, 0.32]}
      />
      <mesh
        name="Sphere_cell021"
        geometry={nodes.Sphere_cell021.geometry}
        material={materials["Material.001"]}
        position={[0.225, 0.903, -0.284]}
      />
      <mesh
        name="Sphere_cell022"
        geometry={nodes.Sphere_cell022.geometry}
        material={materials["Material.001"]}
        position={[-0.683, -0.275, 0.516]}
      />
      <mesh
        name="Sphere_cell023"
        geometry={nodes.Sphere_cell023.geometry}
        material={materials["Material.001"]}
        position={[0.292, -0.329, 0.8]}
      />
      <mesh
        name="Sphere_cell024"
        geometry={nodes.Sphere_cell024.geometry}
        material={materials["Material.001"]}
        position={[-0.824, -0.483, 0.253]}
      />
      <mesh
        name="Sphere_cell026"
        geometry={nodes.Sphere_cell026.geometry}
        material={materials["Material.001"]}
        position={[0.826, -0.118, 0.131]}
      />
      <mesh
        name="Sphere_cell027"
        geometry={nodes.Sphere_cell027.geometry}
        material={materials["Material.001"]}
        position={[0.198, -0.049, 0.396]}
      />
      <mesh
        name="Sphere_cell028"
        geometry={nodes.Sphere_cell028.geometry}
        material={materials["Material.001"]}
        position={[0.026, 0.196, -0.936]}
      />
      <mesh
        name="Sphere_cell029"
        geometry={nodes.Sphere_cell029.geometry}
        material={materials["Material.001"]}
        position={[0.78, -0.323, -0.42]}
      />
      <mesh
        name="Sphere_cell030"
        geometry={nodes.Sphere_cell030.geometry}
        material={materials["Material.001"]}
        position={[0.397, -0.153, -0.281]}
      />
      <mesh
        name="Sphere_cell031"
        geometry={nodes.Sphere_cell031.geometry}
        material={materials["Material.001"]}
        position={[0.712, 0.046, 0.62]}
      />
      <mesh
        name="Sphere_cell032"
        geometry={nodes.Sphere_cell032.geometry}
        material={materials["Material.001"]}
        position={[0.419, 0.784, -0.257]}
      />
      <mesh
        name="Sphere_cell033"
        geometry={nodes.Sphere_cell033.geometry}
        material={materials["Material.001"]}
        position={[0.108, -0.353, -0.66]}
      />
      <mesh
        name="Sphere_cell034"
        geometry={nodes.Sphere_cell034.geometry}
        material={materials["Material.001"]}
        position={[0.705, -0.706, -0.002]}
      />
      <mesh
        name="Sphere_cell035"
        geometry={nodes.Sphere_cell035.geometry}
        material={materials["Material.001"]}
        position={[-0.027, -0.701, -0.445]}
      />
      <mesh
        name="Sphere_cell036"
        geometry={nodes.Sphere_cell036.geometry}
        material={materials["Material.001"]}
        position={[-0.087, 0.964, -0.023]}
      />
      <mesh
        name="Sphere_cell037"
        geometry={nodes.Sphere_cell037.geometry}
        material={materials["Material.001"]}
        position={[-0.576, -0.738, 0.08]}
      />
      <mesh
        name="Sphere_cell038"
        geometry={nodes.Sphere_cell038.geometry}
        material={materials["Material.001"]}
        position={[-0.377, 0.128, 0.529]}
      />
      <mesh
        name="Sphere_cell039"
        geometry={nodes.Sphere_cell039.geometry}
        material={materials["Material.001"]}
        position={[0.451, 0.141, 0.788]}
      />
      <mesh
        name="Sphere_cell040"
        geometry={nodes.Sphere_cell040.geometry}
        material={materials["Material.001"]}
        position={[-0.341, -0.913, 0.016]}
      />
      <mesh
        name="Sphere_cell041"
        geometry={nodes.Sphere_cell041.geometry}
        material={materials["Material.001"]}
        position={[0.646, 0.28, -0.652]}
      />
      <mesh
        name="Sphere_cell043"
        geometry={nodes.Sphere_cell043.geometry}
        material={materials["Material.001"]}
        position={[0.341, -0.806, 0.42]}
      />
      <mesh
        name="Sphere_cell045"
        geometry={nodes.Sphere_cell045.geometry}
        material={materials["Material.001"]}
        position={[0.642, -0.051, -0.627]}
      />
      <mesh
        name="Sphere_cell046"
        geometry={nodes.Sphere_cell046.geometry}
        material={materials["Material.001"]}
        position={[-0.496, -0.346, -0.643]}
      />
      <mesh
        name="Sphere_cell047"
        geometry={nodes.Sphere_cell047.geometry}
        material={materials["Material.001"]}
        position={[0.784, 0.057, -0.411]}
      />
      <mesh
        name="Sphere_cell048"
        geometry={nodes.Sphere_cell048.geometry}
        material={materials["Material.001"]}
        position={[-0.627, 0.172, -0.722]}
      />
      <mesh
        name="Sphere_cell049"
        geometry={nodes.Sphere_cell049.geometry}
        material={materials["Material.001"]}
        position={[0.748, -0.485, -0.199]}
      />
      <mesh
        name="Sphere_cell051"
        geometry={nodes.Sphere_cell051.geometry}
        material={materials["Material.001"]}
        position={[-0.141, -0.477, -0.806]}
      />
      <mesh
        name="Sphere_cell052"
        geometry={nodes.Sphere_cell052.geometry}
        material={materials["Material.001"]}
        position={[-0.556, 0.722, -0.178]}
      />
      <mesh
        name="Sphere_cell053"
        geometry={nodes.Sphere_cell053.geometry}
        material={materials["Material.001"]}
        position={[-0.301, -0.743, -0.549]}
      />
      <mesh
        name="Sphere_cell055"
        geometry={nodes.Sphere_cell055.geometry}
        material={materials["Material.001"]}
        position={[-0.864, 0.216, -0.379]}
      />
      <mesh
        name="Sphere_cell057"
        geometry={nodes.Sphere_cell057.geometry}
        material={materials["Material.001"]}
        position={[-0.727, -0.483, 0.038]}
      />
      <mesh
        name="Sphere_cell058"
        geometry={nodes.Sphere_cell058.geometry}
        material={materials["Material.001"]}
        position={[0.031, 0.886, 0.372]}
      />
      <mesh
        name="Sphere_cell059"
        geometry={nodes.Sphere_cell059.geometry}
        material={materials["Material.001"]}
        position={[-0.309, 0.285, -0.292]}
      />
      <mesh
        name="Sphere_cell060"
        geometry={nodes.Sphere_cell060.geometry}
        material={materials["Material.001"]}
        position={[0.394, -0.622, 0.654]}
      />
      <mesh
        name="Sphere_cell061"
        geometry={nodes.Sphere_cell061.geometry}
        material={materials["Material.001"]}
        position={[-0.013, -0.421, 0.744]}
      />
      <mesh
        name="Sphere_cell062"
        geometry={nodes.Sphere_cell062.geometry}
        material={materials["Material.001"]}
        position={[-0.432, -0.451, 0.186]}
      />
      <mesh
        name="Sphere_cell064"
        geometry={nodes.Sphere_cell064.geometry}
        material={materials["Material.001"]}
        position={[-0.51, 0.609, -0.474]}
      />
      <mesh
        name="Sphere_cell065"
        geometry={nodes.Sphere_cell065.geometry}
        material={materials["Material.001"]}
        position={[-0.652, -0.607, -0.241]}
      />
      <mesh
        name="Sphere_cell067"
        geometry={nodes.Sphere_cell067.geometry}
        material={materials["Material.001"]}
        position={[-0.774, -0.423, -0.299]}
      />
      <mesh
        name="Sphere_cell068"
        geometry={nodes.Sphere_cell068.geometry}
        material={materials["Material.001"]}
        position={[0.264, 0.703, -0.602]}
      />
      <mesh
        name="Sphere_cell069"
        geometry={nodes.Sphere_cell069.geometry}
        material={materials["Material.001"]}
        position={[0.063, -0.862, 0.378]}
      />
      <mesh
        name="Sphere_cell070"
        geometry={nodes.Sphere_cell070.geometry}
        material={materials["Material.001"]}
        position={[0.757, -0.323, 0.457]}
      />
      <mesh
        name="Sphere_cell071"
        geometry={nodes.Sphere_cell071.geometry}
        material={materials["Material.001"]}
        position={[0.213, 0.954, -0.141]}
      />
      <mesh
        name="Sphere_cell072"
        geometry={nodes.Sphere_cell072.geometry}
        material={materials["Material.001"]}
        position={[-0.191, -0.847, -0.441]}
      />
      <mesh
        name="Sphere_cell073"
        geometry={nodes.Sphere_cell073.geometry}
        material={materials["Material.001"]}
        position={[-0.183, -0.94, 0.234]}
      />
      <mesh
        name="Sphere_cell074"
        geometry={nodes.Sphere_cell074.geometry}
        material={materials["Material.001"]}
        position={[0.386, -0.7, 0.593]}
      />
      <mesh
        name="Sphere_cell075"
        geometry={nodes.Sphere_cell075.geometry}
        material={materials["Material.001"]}
        position={[0.275, -0.703, -0.577]}
      />
      <mesh
        name="Sphere_cell077"
        geometry={nodes.Sphere_cell077.geometry}
        material={materials["Material.001"]}
        position={[0.696, 0.518, -0.244]}
      />
      <mesh
        name="Sphere_cell078"
        geometry={nodes.Sphere_cell078.geometry}
        material={materials["Material.001"]}
        position={[0.181, -0.884, -0.405]}
      />
      <mesh
        name="Sphere_cell079"
        geometry={nodes.Sphere_cell079.geometry}
        material={materials["Material.001"]}
        position={[0.165, 0.374, 0.444]}
      />
      <mesh
        name="Sphere_cell080"
        geometry={nodes.Sphere_cell080.geometry}
        material={materials["Material.001"]}
        position={[0.91, 0.066, -0.093]}
      />
      <mesh
        name="Sphere_cell081"
        geometry={nodes.Sphere_cell081.geometry}
        material={materials["Material.001"]}
        position={[0.587, 0.752, 0.233]}
      />
      <mesh
        name="Sphere_cell082"
        geometry={nodes.Sphere_cell082.geometry}
        material={materials["Material.001"]}
        position={[-0.237, -0.709, 0.135]}
      />
      <mesh
        name="Sphere_cell083"
        geometry={nodes.Sphere_cell083.geometry}
        material={materials["Material.001"]}
        position={[-0.323, 0.72, -0.586]}
      />
      <mesh
        name="Sphere_cell084"
        geometry={nodes.Sphere_cell084.geometry}
        material={materials["Material.001"]}
        position={[-0.815, 0.145, 0.384]}
      />
      <mesh
        name="Sphere_cell085"
        geometry={nodes.Sphere_cell085.geometry}
        material={materials["Material.001"]}
        position={[0.529, -0.16, 0.827]}
      />
      <mesh
        name="Sphere_cell086"
        geometry={nodes.Sphere_cell086.geometry}
        material={materials["Material.001"]}
        position={[-0.181, 0, -0.931]}
      />
      <mesh
        name="Sphere_cell087"
        geometry={nodes.Sphere_cell087.geometry}
        material={materials["Material.001"]}
        position={[-0.327, -0.163, 0.059]}
      />
      <mesh
        name="Sphere_cell089"
        geometry={nodes.Sphere_cell089.geometry}
        material={materials["Material.001"]}
        position={[-0.371, 0.802, 0.143]}
      />
      <mesh
        name="Sphere_cell090"
        geometry={nodes.Sphere_cell090.geometry}
        material={materials["Material.001"]}
        position={[0.799, -0.413, 0.21]}
      />
      <mesh
        name="Sphere_cell091"
        geometry={nodes.Sphere_cell091.geometry}
        material={materials["Material.001"]}
        position={[0.399, 0.374, 0.72]}
      />
      <mesh
        name="Sphere_cell092"
        geometry={nodes.Sphere_cell092.geometry}
        material={materials["Material.001"]}
        position={[-0.768, -0.244, -0.53]}
      />
      <mesh
        name="Sphere_cell094"
        geometry={nodes.Sphere_cell094.geometry}
        material={materials["Material.001"]}
        position={[-0.016, 0.567, -0.698]}
      />
      <mesh
        name="Sphere_cell096"
        geometry={nodes.Sphere_cell096.geometry}
        material={materials["Material.001"]}
        position={[-0.481, -0.648, -0.531]}
      />
      <mesh
        name="Sphere_cell098"
        geometry={nodes.Sphere_cell098.geometry}
        material={materials["Material.001"]}
        position={[-0.294, -0.573, -0.238]}
      />
      <mesh
        name="Sphere_cell099"
        geometry={nodes.Sphere_cell099.geometry}
        material={materials["Material.001"]}
        position={[-0.244, 0.577, 0.42]}
      />
      <mesh
        name="Sphere_cell100"
        geometry={nodes.Sphere_cell100.geometry}
        material={materials["Material.001"]}
        position={[-0.614, 0.527, 0.44]}
      />
      <mesh
        name="Sphere_cell101"
        geometry={nodes.Sphere_cell101.geometry}
        material={materials["Material.001"]}
        position={[-0.342, 0.914, 0.016]}
      />
      <mesh
        name="Sphere_cell102"
        geometry={nodes.Sphere_cell102.geometry}
        material={materials["Material.001"]}
        position={[-0.019, -0.228, -0.823]}
      />
      <mesh
        name="Sphere_cell104"
        geometry={nodes.Sphere_cell104.geometry}
        material={materials["Material.001"]}
        position={[-0.68, -0.003, -0.583]}
      />
      <mesh
        name="Sphere_cell105"
        geometry={nodes.Sphere_cell105.geometry}
        material={materials["Material.001"]}
        position={[0.447, 0.237, -0.839]}
      />
      <mesh
        name="Sphere_cell106"
        geometry={nodes.Sphere_cell106.geometry}
        material={materials["Material.001"]}
        position={[-0.359, -0.379, 0.745]}
      />
      <mesh
        name="Sphere_cell109"
        geometry={nodes.Sphere_cell109.geometry}
        material={materials["Material.001"]}
        position={[-0.684, -0.088, -0.329]}
      />
      <mesh
        name="Sphere_cell110"
        geometry={nodes.Sphere_cell110.geometry}
        material={materials["Material.001"]}
        position={[-0.086, 0.625, 0.035]}
      />
      <mesh
        name="Sphere_cell111"
        geometry={nodes.Sphere_cell111.geometry}
        material={materials["Material.001"]}
        position={[-0.738, -0.245, 0.202]}
      />
      <mesh
        name="Sphere_cell112"
        geometry={nodes.Sphere_cell112.geometry}
        material={materials["Material.001"]}
        position={[0.532, 0.643, 0.401]}
      />
      <mesh
        name="Sphere_cell113"
        geometry={nodes.Sphere_cell113.geometry}
        material={materials["Material.001"]}
        position={[-0.15, -0.578, 0.774]}
      />
      <mesh
        name="Sphere_cell115"
        geometry={nodes.Sphere_cell115.geometry}
        material={materials["Material.001"]}
        position={[0.17, 0.862, 0.257]}
      />
      <mesh
        name="Sphere_cell117"
        geometry={nodes.Sphere_cell117.geometry}
        material={materials["Material.001"]}
        position={[-0.007, 0.022, 0.892]}
      />
      <mesh
        name="Sphere_cell119"
        geometry={nodes.Sphere_cell119.geometry}
        material={materials["Material.001"]}
        position={[-0.913, -0.185, 0.119]}
      />
      <mesh
        name="Sphere_cell120"
        geometry={nodes.Sphere_cell120.geometry}
        material={materials["Material.001"]}
        position={[0.438, -0.838, -0.059]}
      />
      <mesh
        name="Sphere_cell121"
        geometry={nodes.Sphere_cell121.geometry}
        material={materials["Material.001"]}
        position={[0.359, -0.763, 0.165]}
      />
      <mesh
        name="Sphere_cell123"
        geometry={nodes.Sphere_cell123.geometry}
        material={materials["Material.001"]}
        position={[0.232, -0.468, -0.221]}
      />
      <mesh
        name="Sphere_cell124"
        geometry={nodes.Sphere_cell124.geometry}
        material={materials["Material.001"]}
        position={[0.505, 0.771, 0.094]}
      />
      <mesh
        name="Sphere_cell125"
        geometry={nodes.Sphere_cell125.geometry}
        material={materials["Material.001"]}
        position={[-0.095, 0.961, 0.166]}
      />
      <mesh
        name="Sphere_cell126"
        geometry={nodes.Sphere_cell126.geometry}
        material={materials["Material.001"]}
        position={[0.01, -0.501, 0.452]}
      />
      <mesh
        name="Sphere_cell127"
        geometry={nodes.Sphere_cell127.geometry}
        material={materials["Material.001"]}
        position={[0.213, 0.338, -0.342]}
      />
      <mesh
        name="Sphere_cell128"
        geometry={nodes.Sphere_cell128.geometry}
        material={materials["Material.001"]}
        position={[0.155, -0.483, 0.259]}
      />
      <mesh
        name="Sphere_cell129"
        geometry={nodes.Sphere_cell129.geometry}
        material={materials["Material.001"]}
        position={[-0.211, -0.342, 0.37]}
      />
      <mesh
        name="Sphere_cell130"
        geometry={nodes.Sphere_cell130.geometry}
        material={materials["Material.001"]}
        position={[0.052, -0.029, -0.107]}
      />
      <mesh
        name="Sphere_cell131"
        geometry={nodes.Sphere_cell131.geometry}
        material={materials["Material.001"]}
        position={[0.194, 0.932, 0.042]}
      />
      <mesh
        name="Sphere_cell132"
        geometry={nodes.Sphere_cell132.geometry}
        material={materials["Material.001"]}
        position={[-0.003, -0.924, -0.022]}
      />
      <mesh
        name="Sphere_cell133"
        geometry={nodes.Sphere_cell133.geometry}
        material={materials["Material.001"]}
        position={[-0.133, 0.527, 0.185]}
      />
      <mesh
        name="Sphere_cell134"
        geometry={nodes.Sphere_cell134.geometry}
        material={materials["Material.001"]}
        position={[0.074, -0.944, 0.134]}
      />
      <mesh
        name="Sphere_cell135"
        geometry={nodes.Sphere_cell135.geometry}
        material={materials["Material.001"]}
        position={[-0.634, 0.301, -0.617]}
      />
      <mesh
        name="Sphere_cell136"
        geometry={nodes.Sphere_cell136.geometry}
        material={materials["Material.001"]}
        position={[-0.088, -0.939, -0.064]}
      />
      <mesh
        name="Sphere_cell137"
        geometry={nodes.Sphere_cell137.geometry}
        material={materials["Material.001"]}
        position={[0.622, -0.457, 0.058]}
      />
      <mesh
        name="Sphere_cell138"
        geometry={nodes.Sphere_cell138.geometry}
        material={materials["Material.001"]}
        position={[0.507, -0.7, -0.357]}
      />
      <mesh
        name="Sphere_cell139"
        geometry={nodes.Sphere_cell139.geometry}
        material={materials["Material.001"]}
        position={[-0.641, -0.643, 0.287]}
      />
      <mesh
        name="Sphere_cell141"
        geometry={nodes.Sphere_cell141.geometry}
        material={materials["Material.001"]}
        position={[0.062, -0.661, -0.722]}
      />
      <mesh
        name="Sphere_cell142"
        geometry={nodes.Sphere_cell142.geometry}
        material={materials["Material.001"]}
        position={[0.197, 0.195, 0.932]}
      />
      <mesh
        name="Sphere_cell143"
        geometry={nodes.Sphere_cell143.geometry}
        material={materials["Material.001"]}
        position={[-0.123, 0.479, 0.783]}
      />
      <mesh
        name="Sphere_cell144"
        geometry={nodes.Sphere_cell144.geometry}
        material={materials["Material.001"]}
        position={[0.023, 0.765, 0.607]}
      />
      <mesh
        name="Sphere_cell145"
        geometry={nodes.Sphere_cell145.geometry}
        material={materials["Material.001"]}
        position={[-0.798, 0.515, 0.275]}
      />
      <mesh
        name="Sphere_cell147"
        geometry={nodes.Sphere_cell147.geometry}
        material={materials["Material.001"]}
        position={[0.503, -0.366, -0.683]}
      />
      <mesh
        name="Sphere_cell148"
        geometry={nodes.Sphere_cell148.geometry}
        material={materials["Material.001"]}
        position={[0.548, -0.685, 0.284]}
      />
      <mesh
        name="Sphere_cell150"
        geometry={nodes.Sphere_cell150.geometry}
        material={materials["Material.001"]}
        position={[-0.43, 0.722, 0.442]}
      />
      <mesh
        name="Sphere_cell153"
        geometry={nodes.Sphere_cell153.geometry}
        material={materials["Material.001"]}
        position={[-0.308, 0.046, -0.779]}
      />
      <mesh
        name="Sphere_cell154"
        geometry={nodes.Sphere_cell154.geometry}
        material={materials["Material.001"]}
        position={[0.748, 0.122, 0.366]}
      />
      <mesh
        name="Sphere_cell157"
        geometry={nodes.Sphere_cell157.geometry}
        material={materials["Material.001"]}
        position={[0.321, 0.788, 0.454]}
      />
      <mesh
        name="Sphere_cell158"
        geometry={nodes.Sphere_cell158.geometry}
        material={materials["Material.001"]}
        position={[0.604, 0.153, -0.14]}
      />
      <mesh
        name="Sphere_cell159"
        geometry={nodes.Sphere_cell159.geometry}
        material={materials["Material.001"]}
        position={[0.832, 0.292, -0.346]}
      />
      <mesh
        name="Sphere_cell161"
        geometry={nodes.Sphere_cell161.geometry}
        material={materials["Material.001"]}
        position={[-0.335, 0.816, -0.264]}
      />
      <mesh
        name="Sphere_cell162"
        geometry={nodes.Sphere_cell162.geometry}
        material={materials["Material.001"]}
        position={[-0.499, -0.804, -0.06]}
      />
      <mesh
        name="Sphere_cell163"
        geometry={nodes.Sphere_cell163.geometry}
        material={materials["Material.001"]}
        position={[0.074, 0.978, -0.141]}
      />
      <mesh
        name="Sphere_cell164"
        geometry={nodes.Sphere_cell164.geometry}
        material={materials["Material.001"]}
        position={[-0.083, -0.344, 0.902]}
      />
      <mesh
        name="Sphere_cell165"
        geometry={nodes.Sphere_cell165.geometry}
        material={materials["Material.001"]}
        position={[0.17, -0.825, -0.273]}
      />
      <mesh
        name="Sphere_cell168"
        geometry={nodes.Sphere_cell168.geometry}
        material={materials["Material.001"]}
        position={[0.161, 0.329, -0.798]}
      />
      <mesh
        name="Sphere_cell169"
        geometry={nodes.Sphere_cell169.geometry}
        material={materials["Material.001"]}
        position={[0.056, 0.017, -0.794]}
      />
      <mesh
        name="Sphere_cell170"
        geometry={nodes.Sphere_cell170.geometry}
        material={materials["Material.001"]}
        position={[0.056, -0.947, -0.214]}
      />
      <mesh
        name="Sphere_cell171"
        geometry={nodes.Sphere_cell171.geometry}
        material={materials["Material.001"]}
        position={[0.201, 0.643, 0.398]}
      />
      <mesh
        name="Sphere_cell174"
        geometry={nodes.Sphere_cell174.geometry}
        material={materials["Material.001"]}
        position={[-0.031, 0.788, -0.463]}
      />
      <mesh
        name="Sphere_cell175"
        geometry={nodes.Sphere_cell175.geometry}
        material={materials["Material.001"]}
        position={[-0.239, 0.478, -0.773]}
      />
      <mesh
        name="Sphere_cell176"
        geometry={nodes.Sphere_cell176.geometry}
        material={materials["Material.001"]}
        position={[-0.631, 0.281, 0.656]}
      />
      <mesh
        name="Sphere_cell178"
        geometry={nodes.Sphere_cell178.geometry}
        material={materials["Material.001"]}
        position={[-0.42, -0.822, -0.295]}
      />
      <mesh
        name="Sphere_cell179"
        geometry={nodes.Sphere_cell179.geometry}
        material={materials["Material.001"]}
        position={[0.368, 0.004, -0.811]}
      />
      <mesh
        name="Sphere_cell180"
        geometry={nodes.Sphere_cell180.geometry}
        material={materials["Material.001"]}
        position={[-0.823, 0.389, -0.009]}
      />
      <mesh
        name="Sphere_cell181"
        geometry={nodes.Sphere_cell181.geometry}
        material={materials["Material.001"]}
        position={[0.229, -0.84, -0.1]}
      />
      <mesh
        name="Sphere_cell182"
        geometry={nodes.Sphere_cell182.geometry}
        material={materials["Material.001"]}
        position={[0.301, 0.625, 0.658]}
      />
      <mesh
        name="Sphere_cell183"
        geometry={nodes.Sphere_cell183.geometry}
        material={materials["Material.001"]}
        position={[0.109, -0.682, 0.634]}
      />
      <mesh
        name="Sphere_cell184"
        geometry={nodes.Sphere_cell184.geometry}
        material={materials["Material.001"]}
        position={[-0.587, -0.043, -0.754]}
      />
      <mesh
        name="Sphere_cell187"
        geometry={nodes.Sphere_cell187.geometry}
        material={materials["Material.001"]}
        position={[0.46, 0.427, -0.606]}
      />
      <mesh
        name="Sphere_cell188"
        geometry={nodes.Sphere_cell188.geometry}
        material={materials["Material.001"]}
        position={[0.489, -0.15, 0.574]}
      />
      <mesh
        name="Sphere_cell189"
        geometry={nodes.Sphere_cell189.geometry}
        material={materials["Material.001"]}
        position={[-0.118, -0.968, -0.198]}
      />
    </group>
  );
}

useGLTF.preload("/Lava/lava.glb");
