/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/Stone/stone.glb -o src/component/canvas/Stone.jsx -r public -k 
*/

import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import React, { useRef } from "react";
import { useExplode } from "../hooks/useExplode";

export function Stone(props) {
  const { nodes, materials } = useGLTF("/Stone/stone.glb");
  const group = useRef();
  const { bluebirddistance } = useControls({
    bluebirddistance: {
      value: 2.4,
      min: 0,
      max: 10,
    },
  });
  useExplode(group, {
    distance: bluebirddistance,
    rotationEnabled: true,
  });
  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="origin"
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="Sphere_cell"
        geometry={nodes.Sphere_cell.geometry}
        material={materials["Material.001"]}
        position={[0.29, 0.095, -0.872]}
      />
      <mesh
        name="Sphere_cell002"
        geometry={nodes.Sphere_cell002.geometry}
        material={materials["Material.001"]}
        position={[-0.11, -0.336, -0.925]}
      />
      <mesh
        name="Sphere_cell003"
        geometry={nodes.Sphere_cell003.geometry}
        material={materials["Material.001"]}
        position={[0.856, 0.352, -0.106]}
      />
      <mesh
        name="Sphere_cell004"
        geometry={nodes.Sphere_cell004.geometry}
        material={materials["Material.001"]}
        position={[0.813, -0.513, 0.027]}
      />
      <mesh
        name="Sphere_cell009"
        geometry={nodes.Sphere_cell009.geometry}
        material={materials["Material.001"]}
        position={[0.649, -0.696, 0.089]}
      />
      <mesh
        name="Sphere_cell010"
        geometry={nodes.Sphere_cell010.geometry}
        material={materials["Material.001"]}
        position={[-0.183, 0.135, 0.908]}
      />
      <mesh
        name="Sphere_cell011"
        geometry={nodes.Sphere_cell011.geometry}
        material={materials["Material.001"]}
        position={[0.346, 0.493, 0.108]}
      />
      <mesh
        name="Sphere_cell012"
        geometry={nodes.Sphere_cell012.geometry}
        material={materials["Material.001"]}
        position={[0.163, -0.823, 0.086]}
      />
      <mesh
        name="Sphere_cell013"
        geometry={nodes.Sphere_cell013.geometry}
        material={materials["Material.001"]}
        position={[0.474, 0.801, -0.074]}
      />
      <mesh
        name="Sphere_cell015"
        geometry={nodes.Sphere_cell015.geometry}
        material={materials["Material.001"]}
        position={[-0.133, 0.299, 0.579]}
      />
      <mesh
        name="Sphere_cell016"
        geometry={nodes.Sphere_cell016.geometry}
        material={materials["Material.001"]}
        position={[0.839, 0.185, -0.397]}
      />
      <mesh
        name="Sphere_cell017"
        geometry={nodes.Sphere_cell017.geometry}
        material={materials["Material.001"]}
        position={[0.036, -0.159, 0.939]}
      />
      <mesh
        name="Sphere_cell018"
        geometry={nodes.Sphere_cell018.geometry}
        material={materials["Material.001"]}
        position={[-0.756, 0.254, 0.551]}
      />
      <mesh
        name="Sphere_cell019"
        geometry={nodes.Sphere_cell019.geometry}
        material={materials["Material.001"]}
        position={[0.136, 0.053, 0.79]}
      />
      <mesh
        name="Sphere_cell021"
        geometry={nodes.Sphere_cell021.geometry}
        material={materials["Material.001"]}
        position={[0.055, -0.926, 0.152]}
      />
      <mesh
        name="Sphere_cell022"
        geometry={nodes.Sphere_cell022.geometry}
        material={materials["Material.001"]}
        position={[0.482, 0.804, -0.313]}
      />
      <mesh
        name="Sphere_cell023"
        geometry={nodes.Sphere_cell023.geometry}
        material={materials["Material.001"]}
        position={[-0.681, 0.586, 0.159]}
      />
      <mesh
        name="Sphere_cell024"
        geometry={nodes.Sphere_cell024.geometry}
        material={materials["Material.001"]}
        position={[-0.441, -0.768, -0.391]}
      />
      <mesh
        name="Sphere_cell025"
        geometry={nodes.Sphere_cell025.geometry}
        material={materials["Material.001"]}
        position={[-0.616, -0.379, -0.618]}
      />
      <mesh
        name="Sphere_cell027"
        geometry={nodes.Sphere_cell027.geometry}
        material={materials["Material.001"]}
        position={[-0.138, 0.963, -0.08]}
      />
      <mesh
        name="Sphere_cell028"
        geometry={nodes.Sphere_cell028.geometry}
        material={materials["Material.001"]}
        position={[0.654, 0.714, -0.052]}
      />
      <mesh
        name="Sphere_cell031"
        geometry={nodes.Sphere_cell031.geometry}
        material={materials["Material.001"]}
        position={[0.261, 0.258, 0.46]}
      />
      <mesh
        name="Sphere_cell032"
        geometry={nodes.Sphere_cell032.geometry}
        material={materials["Material.001"]}
        position={[-0.119, -0.542, 0.756]}
      />
      <mesh
        name="Sphere_cell034"
        geometry={nodes.Sphere_cell034.geometry}
        material={materials["Material.001"]}
        position={[-0.415, -0.846, -0.136]}
      />
      <mesh
        name="Sphere_cell035"
        geometry={nodes.Sphere_cell035.geometry}
        material={materials["Material.001"]}
        position={[-0.578, -0.277, 0.003]}
      />
      <mesh
        name="Sphere_cell036"
        geometry={nodes.Sphere_cell036.geometry}
        material={materials["Material.001"]}
        position={[0.338, -0.538, -0.653]}
      />
      <mesh
        name="Sphere_cell038"
        geometry={nodes.Sphere_cell038.geometry}
        material={materials["Material.001"]}
        position={[-0.021, 0.576, 0.418]}
      />
      <mesh
        name="Sphere_cell039"
        geometry={nodes.Sphere_cell039.geometry}
        material={materials["Material.001"]}
        position={[0.166, 0.534, -0.78]}
      />
      <mesh
        name="Sphere_cell040"
        geometry={nodes.Sphere_cell040.geometry}
        material={materials["Material.001"]}
        position={[-0.109, -0.765, -0.519]}
      />
      <mesh
        name="Sphere_cell041"
        geometry={nodes.Sphere_cell041.geometry}
        material={materials["Material.001"]}
        position={[0.187, -0.365, -0.871]}
      />
      <mesh
        name="Sphere_cell042"
        geometry={nodes.Sphere_cell042.geometry}
        material={materials["Material.001"]}
        position={[0.596, -0.289, -0.572]}
      />
      <mesh
        name="Sphere_cell043"
        geometry={nodes.Sphere_cell043.geometry}
        material={materials["Material.001"]}
        position={[-0.784, 0.051, 0.203]}
      />
      <mesh
        name="Sphere_cell044"
        geometry={nodes.Sphere_cell044.geometry}
        material={materials["Material.001"]}
        position={[0.442, 0.782, 0.153]}
      />
      <mesh
        name="Sphere_cell045"
        geometry={nodes.Sphere_cell045.geometry}
        material={materials["Material.001"]}
        position={[0.228, -0.706, -0.662]}
      />
      <mesh
        name="Sphere_cell046"
        geometry={nodes.Sphere_cell046.geometry}
        material={materials["Material.001"]}
        position={[-0.299, -0.651, 0.573]}
      />
      <mesh
        name="Sphere_cell047"
        geometry={nodes.Sphere_cell047.geometry}
        material={materials["Material.001"]}
        position={[0.359, -0.37, 0.363]}
      />
      <mesh
        name="Sphere_cell051"
        geometry={nodes.Sphere_cell051.geometry}
        material={materials["Material.001"]}
        position={[0.343, 0.725, -0.474]}
      />
      <mesh
        name="Sphere_cell052"
        geometry={nodes.Sphere_cell052.geometry}
        material={materials["Material.001"]}
        position={[0.584, -0.14, -0.753]}
      />
      <mesh
        name="Sphere_cell053"
        geometry={nodes.Sphere_cell053.geometry}
        material={materials["Material.001"]}
        position={[0.903, 0.048, -0.214]}
      />
      <mesh
        name="Sphere_cell054"
        geometry={nodes.Sphere_cell054.geometry}
        material={materials["Material.001"]}
        position={[0.495, -0.653, -0.228]}
      />
      <mesh
        name="Sphere_cell055"
        geometry={nodes.Sphere_cell055.geometry}
        material={materials["Material.001"]}
        position={[0.336, -0.56, 0.004]}
      />
      <mesh
        name="Sphere_cell056"
        geometry={nodes.Sphere_cell056.geometry}
        material={materials["Material.001"]}
        position={[-0.222, 0.901, -0.281]}
      />
      <mesh
        name="Sphere_cell057"
        geometry={nodes.Sphere_cell057.geometry}
        material={materials["Material.001"]}
        position={[-0.207, -0.365, 0.9]}
      />
      <mesh
        name="Sphere_cell060"
        geometry={nodes.Sphere_cell060.geometry}
        material={materials["Material.001"]}
        position={[0.579, -0.059, -0.134]}
      />
      <mesh
        name="Sphere_cell062"
        geometry={nodes.Sphere_cell062.geometry}
        material={materials["Material.001"]}
        position={[-0.271, 0.064, -0.703]}
      />
      <mesh
        name="Sphere_cell063"
        geometry={nodes.Sphere_cell063.geometry}
        material={materials["Material.001"]}
        position={[0, -0.072, -0.928]}
      />
      <mesh
        name="Sphere_cell064"
        geometry={nodes.Sphere_cell064.geometry}
        material={materials["Material.001"]}
        position={[-0.418, 0.808, 0.284]}
      />
      <mesh
        name="Sphere_cell065"
        geometry={nodes.Sphere_cell065.geometry}
        material={materials["Material.001"]}
        position={[0.694, 0.588, 0.093]}
      />
      <mesh
        name="Sphere_cell067"
        geometry={nodes.Sphere_cell067.geometry}
        material={materials["Material.001"]}
        position={[-0.914, -0.237, -0.274]}
      />
      <mesh
        name="Sphere_cell068"
        geometry={nodes.Sphere_cell068.geometry}
        material={materials["Material.001"]}
        position={[0.524, 0.774, 0.265]}
      />
      <mesh
        name="Sphere_cell069"
        geometry={nodes.Sphere_cell069.geometry}
        material={materials["Material.001"]}
        position={[0.077, -0.675, 0.527]}
      />
      <mesh
        name="Sphere_cell070"
        geometry={nodes.Sphere_cell070.geometry}
        material={materials["Material.001"]}
        position={[-0.653, 0.593, -0.379]}
      />
      <mesh
        name="Sphere_cell071"
        geometry={nodes.Sphere_cell071.geometry}
        material={materials["Material.001"]}
        position={[0.122, 0.396, 0.801]}
      />
      <mesh
        name="Sphere_cell072"
        geometry={nodes.Sphere_cell072.geometry}
        material={materials["Material.001"]}
        position={[0.642, -0.692, -0.138]}
      />
      <mesh
        name="Sphere_cell074"
        geometry={nodes.Sphere_cell074.geometry}
        material={materials["Material.001"]}
        position={[0.801, -0.339, 0.443]}
      />
      <mesh
        name="Sphere_cell076"
        geometry={nodes.Sphere_cell076.geometry}
        material={materials["Material.001"]}
        position={[0.239, 0.856, 0.139]}
      />
      <mesh
        name="Sphere_cell077"
        geometry={nodes.Sphere_cell077.geometry}
        material={materials["Material.001"]}
        position={[0.621, -0.534, -0.437]}
      />
      <mesh
        name="Sphere_cell081"
        geometry={nodes.Sphere_cell081.geometry}
        material={materials["Material.001"]}
        position={[-0.007, -0.435, 0.778]}
      />
      <mesh
        name="Sphere_cell084"
        geometry={nodes.Sphere_cell084.geometry}
        material={materials["Material.001"]}
        position={[0.112, -0.957, -0.168]}
      />
      <mesh
        name="Sphere_cell085"
        geometry={nodes.Sphere_cell085.geometry}
        material={materials["Material.001"]}
        position={[0.316, 0.935, 0.001]}
      />
      <mesh
        name="Sphere_cell086"
        geometry={nodes.Sphere_cell086.geometry}
        material={materials["Material.001"]}
        position={[0.301, -0.461, -0.331]}
      />
      <mesh
        name="Sphere_cell087"
        geometry={nodes.Sphere_cell087.geometry}
        material={materials["Material.001"]}
        position={[0.116, -0.218, -0.453]}
      />
      <mesh
        name="Sphere_cell088"
        geometry={nodes.Sphere_cell088.geometry}
        material={materials["Material.001"]}
        position={[0.06, 0.639, 0.696]}
      />
      <mesh
        name="Sphere_cell089"
        geometry={nodes.Sphere_cell089.geometry}
        material={materials["Material.001"]}
        position={[-0.225, -0.149, -0.888]}
      />
      <mesh
        name="Sphere_cell090"
        geometry={nodes.Sphere_cell090.geometry}
        material={materials["Material.001"]}
        position={[0.246, -0.319, 0.831]}
      />
      <mesh
        name="Sphere_cell091"
        geometry={nodes.Sphere_cell091.geometry}
        material={materials["Material.001"]}
        position={[0.369, -0.862, -0.167]}
      />
      <mesh
        name="Sphere_cell093"
        geometry={nodes.Sphere_cell093.geometry}
        material={materials["Material.001"]}
        position={[0.58, 0.712, -0.31]}
      />
      <mesh
        name="Sphere_cell096"
        geometry={nodes.Sphere_cell096.geometry}
        material={materials["Material.001"]}
        position={[-0.7, -0.435, 0.134]}
      />
      <mesh
        name="Sphere_cell097"
        geometry={nodes.Sphere_cell097.geometry}
        material={materials["Material.001"]}
        position={[0.193, -0.584, 0.771]}
      />
      <mesh
        name="Sphere_cell098"
        geometry={nodes.Sphere_cell098.geometry}
        material={materials["Material.001"]}
        position={[0.271, -0.815, 0.212]}
      />
      <mesh
        name="Sphere_cell100"
        geometry={nodes.Sphere_cell100.geometry}
        material={materials["Material.001"]}
        position={[-0.673, -0.008, -0.131]}
      />
      <mesh
        name="Sphere_cell101"
        geometry={nodes.Sphere_cell101.geometry}
        material={materials["Material.001"]}
        position={[0.922, -0.15, -0.246]}
      />
      <mesh
        name="Sphere_cell102"
        geometry={nodes.Sphere_cell102.geometry}
        material={materials["Material.001"]}
        position={[0.031, 0.316, -0.85]}
      />
      <mesh
        name="Sphere_cell103"
        geometry={nodes.Sphere_cell103.geometry}
        material={materials["Material.001"]}
        position={[-0.839, -0.4, 0.008]}
      />
      <mesh
        name="Sphere_cell104"
        geometry={nodes.Sphere_cell104.geometry}
        material={materials["Material.001"]}
        position={[0.81, -0.413, -0.207]}
      />
      <mesh
        name="Sphere_cell105"
        geometry={nodes.Sphere_cell105.geometry}
        material={materials["Material.001"]}
        position={[-0.268, -0.147, 0.892]}
      />
      <mesh
        name="Sphere_cell106"
        geometry={nodes.Sphere_cell106.geometry}
        material={materials["Material.001"]}
        position={[0.687, -0.001, 0.675]}
      />
      <mesh
        name="Sphere_cell107"
        geometry={nodes.Sphere_cell107.geometry}
        material={materials["Material.001"]}
        position={[0.15, 0.61, -0.664]}
      />
      <mesh
        name="Sphere_cell108"
        geometry={nodes.Sphere_cell108.geometry}
        material={materials["Material.001"]}
        position={[-0.228, 0.224, -0.188]}
      />
      <mesh
        name="Sphere_cell109"
        geometry={nodes.Sphere_cell109.geometry}
        material={materials["Material.001"]}
        position={[-0.429, -0.307, -0.447]}
      />
      <mesh
        name="Sphere_cell110"
        geometry={nodes.Sphere_cell110.geometry}
        material={materials["Material.001"]}
        position={[-0.226, -0.164, 0.515]}
      />
      <mesh
        name="Sphere_cell111"
        geometry={nodes.Sphere_cell111.geometry}
        material={materials["Material.001"]}
        position={[-0.094, -0.511, -0.384]}
      />
      <mesh
        name="Sphere_cell112"
        geometry={nodes.Sphere_cell112.geometry}
        material={materials["Material.001"]}
        position={[0.119, -0.55, 0.785]}
      />
      <mesh
        name="Sphere_cell113"
        geometry={nodes.Sphere_cell113.geometry}
        material={materials["Material.001"]}
        position={[-0.633, 0.616, 0.379]}
      />
      <mesh
        name="Sphere_cell115"
        geometry={nodes.Sphere_cell115.geometry}
        material={materials["Material.001"]}
        position={[0.852, 0.003, 0.416]}
      />
      <mesh
        name="Sphere_cell116"
        geometry={nodes.Sphere_cell116.geometry}
        material={materials["Material.001"]}
        position={[-0.843, -0.396, 0.26]}
      />
      <mesh
        name="Sphere_cell118"
        geometry={nodes.Sphere_cell118.geometry}
        material={materials["Material.001"]}
        position={[0.002, 0.933, 0.179]}
      />
      <mesh
        name="Sphere_cell119"
        geometry={nodes.Sphere_cell119.geometry}
        material={materials["Material.001"]}
        position={[-0.776, -0.216, -0.429]}
      />
      <mesh
        name="Sphere_cell120"
        geometry={nodes.Sphere_cell120.geometry}
        material={materials["Material.001"]}
        position={[0.016, -0.977, -0.029]}
      />
      <mesh
        name="Sphere_cell121"
        geometry={nodes.Sphere_cell121.geometry}
        material={materials["Material.001"]}
        position={[-0.469, 0.536, -0.237]}
      />
      <mesh
        name="Sphere_cell122"
        geometry={nodes.Sphere_cell122.geometry}
        material={materials["Material.001"]}
        position={[0.227, -0.148, -0.806]}
      />
      <mesh
        name="Sphere_cell123"
        geometry={nodes.Sphere_cell123.geometry}
        material={materials["Material.001"]}
        position={[0.064, -0.833, -0.445]}
      />
      <mesh
        name="Sphere_cell124"
        geometry={nodes.Sphere_cell124.geometry}
        material={materials["Material.001"]}
        position={[0.864, 0.254, 0.368]}
      />
      <mesh
        name="Sphere_cell125"
        geometry={nodes.Sphere_cell125.geometry}
        material={materials["Material.001"]}
        position={[-0.356, 0.484, 0.776]}
      />
      <mesh
        name="Sphere_cell126"
        geometry={nodes.Sphere_cell126.geometry}
        material={materials["Material.001"]}
        position={[-0.218, -0.896, 0.26]}
      />
      <mesh
        name="Sphere_cell127"
        geometry={nodes.Sphere_cell127.geometry}
        material={materials["Material.001"]}
        position={[0.31, -0.751, -0.363]}
      />
      <mesh
        name="Sphere_cell128"
        geometry={nodes.Sphere_cell128.geometry}
        material={materials["Material.001"]}
        position={[-0.601, 0.252, -0.676]}
      />
      <mesh
        name="Sphere_cell129"
        geometry={nodes.Sphere_cell129.geometry}
        material={materials["Material.001"]}
        position={[0.64, -0.201, 0.547]}
      />
      <mesh
        name="Sphere_cell130"
        geometry={nodes.Sphere_cell130.geometry}
        material={materials["Material.001"]}
        position={[0.347, 0.904, 0.117]}
      />
      <mesh
        name="Sphere_cell133"
        geometry={nodes.Sphere_cell133.geometry}
        material={materials["Material.001"]}
        position={[-0.075, -0.651, -0.256]}
      />
      <mesh
        name="Sphere_cell134"
        geometry={nodes.Sphere_cell134.geometry}
        material={materials["Material.001"]}
        position={[0.482, -0.364, -0.75]}
      />
      <mesh
        name="Sphere_cell135"
        geometry={nodes.Sphere_cell135.geometry}
        material={materials["Material.001"]}
        position={[-0.104, -0.927, 0.273]}
      />
      <mesh
        name="Sphere_cell136"
        geometry={nodes.Sphere_cell136.geometry}
        material={materials["Material.001"]}
        position={[-0.51, 0.786, -0.151]}
      />
      <mesh
        name="Sphere_cell142"
        geometry={nodes.Sphere_cell142.geometry}
        material={materials["Material.001"]}
        position={[-0.356, -0.568, -0.7]}
      />
      <mesh
        name="Sphere_cell143"
        geometry={nodes.Sphere_cell143.geometry}
        material={materials["Material.001"]}
        position={[0.354, 0.794, -0.243]}
      />
      <mesh
        name="Sphere_cell145"
        geometry={nodes.Sphere_cell145.geometry}
        material={materials["Material.001"]}
        position={[0.015, -0.41, 0.149]}
      />
      <mesh
        name="Sphere_cell146"
        geometry={nodes.Sphere_cell146.geometry}
        material={materials["Material.001"]}
        position={[-0.257, -0.805, 0.348]}
      />
      <mesh
        name="Sphere_cell148"
        geometry={nodes.Sphere_cell148.geometry}
        material={materials["Material.001"]}
        position={[-0.812, 0.409, -0.382]}
      />
      <mesh
        name="Sphere_cell149"
        geometry={nodes.Sphere_cell149.geometry}
        material={materials["Material.001"]}
        position={[0.421, 0.089, 0.819]}
      />
      <mesh
        name="Sphere_cell150"
        geometry={nodes.Sphere_cell150.geometry}
        material={materials["Material.001"]}
        position={[-0.733, -0.421, -0.393]}
      />
      <mesh
        name="Sphere_cell151"
        geometry={nodes.Sphere_cell151.geometry}
        material={materials["Material.001"]}
        position={[-0.019, 0.983, -0.019]}
      />
      <mesh
        name="Sphere_cell152"
        geometry={nodes.Sphere_cell152.geometry}
        material={materials["Material.001"]}
        position={[-0.592, 0.079, 0.788]}
      />
      <mesh
        name="Sphere_cell153"
        geometry={nodes.Sphere_cell153.geometry}
        material={materials["Material.001"]}
        position={[-0.201, 0.52, 0.758]}
      />
      <mesh
        name="Sphere_cell155"
        geometry={nodes.Sphere_cell155.geometry}
        material={materials["Material.001"]}
        position={[0.125, -0.905, 0.331]}
      />
      <mesh
        name="Sphere_cell157"
        geometry={nodes.Sphere_cell157.geometry}
        material={materials["Material.001"]}
        position={[-0.235, -0.942, -0.184]}
      />
      <mesh
        name="Sphere_cell158"
        geometry={nodes.Sphere_cell158.geometry}
        material={materials["Material.001"]}
        position={[0.792, -0.382, -0.444]}
      />
      <mesh
        name="Sphere_cell159"
        geometry={nodes.Sphere_cell159.geometry}
        material={materials["Material.001"]}
        position={[-0.675, -0.62, 0.289]}
      />
      <mesh
        name="Sphere_cell160"
        geometry={nodes.Sphere_cell160.geometry}
        material={materials["Material.001"]}
        position={[0.108, -0.76, -0.181]}
      />
      <mesh
        name="Sphere_cell161"
        geometry={nodes.Sphere_cell161.geometry}
        material={materials["Material.001"]}
        position={[0.086, 0.682, -0.024]}
      />
      <mesh
        name="Sphere_cell162"
        geometry={nodes.Sphere_cell162.geometry}
        material={materials["Material.001"]}
        position={[-0.204, 0.488, -0.409]}
      />
      <mesh
        name="Sphere_cell164"
        geometry={nodes.Sphere_cell164.geometry}
        material={materials["Material.001"]}
        position={[-0.122, 0.818, 0.479]}
      />
      <mesh
        name="Sphere_cell165"
        geometry={nodes.Sphere_cell165.geometry}
        material={materials["Material.001"]}
        position={[-0.159, -0.9, -0.013]}
      />
      <mesh
        name="Sphere_cell166"
        geometry={nodes.Sphere_cell166.geometry}
        material={materials["Material.001"]}
        position={[-0.391, -0.64, -0.535]}
      />
      <mesh
        name="Sphere_cell167"
        geometry={nodes.Sphere_cell167.geometry}
        material={materials["Material.001"]}
        position={[0.806, -0.309, 0.247]}
      />
      <mesh
        name="Sphere_cell170"
        geometry={nodes.Sphere_cell170.geometry}
        material={materials["Material.001"]}
        position={[0.608, 0.069, -0.607]}
      />
      <mesh
        name="Sphere_cell171"
        geometry={nodes.Sphere_cell171.geometry}
        material={materials["Material.001"]}
        position={[-0.14, 0.306, -0.921]}
      />
      <mesh
        name="Sphere_cell172"
        geometry={nodes.Sphere_cell172.geometry}
        material={materials["Material.001"]}
        position={[-0.855, -0.163, 0.257]}
      />
      <mesh
        name="Sphere_cell173"
        geometry={nodes.Sphere_cell173.geometry}
        material={materials["Material.001"]}
        position={[-0.411, 0.57, 0.379]}
      />
      <mesh
        name="Sphere_cell174"
        geometry={nodes.Sphere_cell174.geometry}
        material={materials["Material.001"]}
        position={[-0.097, -0.444, -0.749]}
      />
      <mesh
        name="Sphere_cell175"
        geometry={nodes.Sphere_cell175.geometry}
        material={materials["Material.001"]}
        position={[0.11, 0.748, -0.497]}
      />
      <mesh
        name="Sphere_cell176"
        geometry={nodes.Sphere_cell176.geometry}
        material={materials["Material.001"]}
        position={[0.463, -0.447, 0.733]}
      />
      <mesh
        name="Sphere_cell177"
        geometry={nodes.Sphere_cell177.geometry}
        material={materials["Material.001"]}
        position={[-0.898, 0.173, -0.299]}
      />
      <mesh
        name="Sphere_cell178"
        geometry={nodes.Sphere_cell178.geometry}
        material={materials["Material.001"]}
        position={[0.364, 0.345, 0.841]}
      />
      <mesh
        name="Sphere_cell180"
        geometry={nodes.Sphere_cell180.geometry}
        material={materials["Material.001"]}
        position={[0.677, 0.294, -0.616]}
      />
      <mesh
        name="Sphere_cell181"
        geometry={nodes.Sphere_cell181.geometry}
        material={materials["Material.001"]}
        position={[0.141, -0.662, -0.719]}
      />
      <mesh
        name="Sphere_cell182"
        geometry={nodes.Sphere_cell182.geometry}
        material={materials["Material.001"]}
        position={[0.277, -0.705, -0.51]}
      />
      <mesh
        name="Sphere_cell183"
        geometry={nodes.Sphere_cell183.geometry}
        material={materials["Material.001"]}
        position={[-0.337, 0.797, -0.413]}
      />
      <mesh
        name="Sphere_cell185"
        geometry={nodes.Sphere_cell185.geometry}
        material={materials["Material.001"]}
        position={[-0.162, 0.691, -0.148]}
      />
      <mesh
        name="Sphere_cell186"
        geometry={nodes.Sphere_cell186.geometry}
        material={materials["Material.001"]}
        position={[-0.217, 0.662, 0.673]}
      />
      <mesh
        name="Sphere_cell187"
        geometry={nodes.Sphere_cell187.geometry}
        material={materials["Material.001"]}
        position={[-0.019, 0.841, -0.406]}
      />
      <mesh
        name="Sphere_cell188"
        geometry={nodes.Sphere_cell188.geometry}
        material={materials["Material.001"]}
        position={[-0.244, 0.387, -0.71]}
      />
      <mesh
        name="Sphere_cell190"
        geometry={nodes.Sphere_cell190.geometry}
        material={materials["Material.001"]}
        position={[-0.013, -0.933, -0.241]}
      />
      <mesh
        name="Sphere_cell193"
        geometry={nodes.Sphere_cell193.geometry}
        material={materials["Material.001"]}
        position={[-0.323, -0.412, 0.805]}
      />
      <mesh
        name="Sphere_cell195"
        geometry={nodes.Sphere_cell195.geometry}
        material={materials["Material.001"]}
        position={[0.422, -0.836, 0.163]}
      />
      <mesh
        name="Sphere_cell196"
        geometry={nodes.Sphere_cell196.geometry}
        material={materials["Material.001"]}
        position={[0.684, 0.134, 0.45]}
      />
      <mesh
        name="Sphere_cell198"
        geometry={nodes.Sphere_cell198.geometry}
        material={materials["Material.001"]}
        position={[0.716, 0.387, 0.35]}
      />
      <mesh
        name="Sphere_cell200"
        geometry={nodes.Sphere_cell200.geometry}
        material={materials["Material.001"]}
        position={[-0.428, 0.514, 0.005]}
      />
      <mesh
        name="Sphere_cell201"
        geometry={nodes.Sphere_cell201.geometry}
        material={materials["Material.001"]}
        position={[-0.307, 0.554, 0.543]}
      />
      <mesh
        name="Sphere_cell204"
        geometry={nodes.Sphere_cell204.geometry}
        material={materials["Material.001"]}
        position={[0.225, -0.941, -0.034]}
      />
      <mesh
        name="Sphere_cell205"
        geometry={nodes.Sphere_cell205.geometry}
        material={materials["Material.001"]}
        position={[0.025, -0.818, 0.401]}
      />
      <mesh
        name="Sphere_cell208"
        geometry={nodes.Sphere_cell208.geometry}
        material={materials["Material.001"]}
        position={[0.184, -0.881, -0.359]}
      />
      <mesh
        name="Sphere_cell209"
        geometry={nodes.Sphere_cell209.geometry}
        material={materials["Material.001"]}
        position={[-0.527, -0.14, 0.732]}
      />
      <mesh
        name="Sphere_cell210"
        geometry={nodes.Sphere_cell210.geometry}
        material={materials["Material.001"]}
        position={[0.492, 0.43, 0.672]}
      />
      <mesh
        name="Sphere_cell211"
        geometry={nodes.Sphere_cell211.geometry}
        material={materials["Material.001"]}
        position={[-0.636, -0.581, -0.419]}
      />
      <mesh
        name="Sphere_cell212"
        geometry={nodes.Sphere_cell212.geometry}
        material={materials["Material.001"]}
        position={[0.053, 0.577, -0.347]}
      />
      <mesh
        name="Sphere_cell215"
        geometry={nodes.Sphere_cell215.geometry}
        material={materials["Material.001"]}
        position={[-0.145, 0.341, 0.886]}
      />
      <mesh
        name="Sphere_cell217"
        geometry={nodes.Sphere_cell217.geometry}
        material={materials["Material.001"]}
        position={[-0.771, -0.085, 0.541]}
      />
      <mesh
        name="Sphere_cell218"
        geometry={nodes.Sphere_cell218.geometry}
        material={materials["Material.001"]}
        position={[-0.461, 0.52, 0.671]}
      />
      <mesh
        name="Sphere_cell219"
        geometry={nodes.Sphere_cell219.geometry}
        material={materials["Material.001"]}
        position={[-0.251, 0.906, 0.05]}
      />
      <mesh
        name="Sphere_cell220"
        geometry={nodes.Sphere_cell220.geometry}
        material={materials["Material.001"]}
        position={[-0.593, -0.644, -0.095]}
      />
      <mesh
        name="Sphere_cell221"
        geometry={nodes.Sphere_cell221.geometry}
        material={materials["Material.001"]}
        position={[0.179, 0.297, -0.427]}
      />
      <mesh
        name="Sphere_cell224"
        geometry={nodes.Sphere_cell224.geometry}
        material={materials["Material.001"]}
        position={[-0.894, 0.339, 0.125]}
      />
      <mesh
        name="Sphere_cell225"
        geometry={nodes.Sphere_cell225.geometry}
        material={materials["Material.001"]}
        position={[-0.432, 0.664, 0.529]}
      />
      <mesh
        name="Sphere_cell226"
        geometry={nodes.Sphere_cell226.geometry}
        material={materials["Material.001"]}
        position={[0.693, 0.199, 0.669]}
      />
      <mesh
        name="Sphere_cell227"
        geometry={nodes.Sphere_cell227.geometry}
        material={materials["Material.001"]}
        position={[-0.441, -0.497, 0.546]}
      />
      <mesh
        name="Sphere_cell228"
        geometry={nodes.Sphere_cell228.geometry}
        material={materials["Material.001"]}
        position={[0.067, -0.164, 0.499]}
      />
      <mesh
        name="Sphere_cell230"
        geometry={nodes.Sphere_cell230.geometry}
        material={materials["Material.001"]}
        position={[0.216, 0.27, 0.928]}
      />
      <mesh
        name="Sphere_cell232"
        geometry={nodes.Sphere_cell232.geometry}
        material={materials["Material.001"]}
        position={[0.103, 0.916, -0.244]}
      />
      <mesh
        name="Sphere_cell233"
        geometry={nodes.Sphere_cell233.geometry}
        material={materials["Material.001"]}
        position={[-0.482, 0.322, 0.293]}
      />
      <mesh
        name="Sphere_cell235"
        geometry={nodes.Sphere_cell235.geometry}
        material={materials["Material.001"]}
        position={[-0.154, 0.725, -0.57]}
      />
      <mesh
        name="Sphere_cell236"
        geometry={nodes.Sphere_cell236.geometry}
        material={materials["Material.001"]}
        position={[-0.036, -0.651, 0.687]}
      />
      <mesh
        name="Sphere_cell238"
        geometry={nodes.Sphere_cell238.geometry}
        material={materials["Material.001"]}
        position={[-0.507, 0.42, -0.699]}
      />
      <mesh
        name="Sphere_cell239"
        geometry={nodes.Sphere_cell239.geometry}
        material={materials["Material.001"]}
        position={[0.12, 0.795, 0.525]}
      />
      <mesh
        name="Sphere_cell241"
        geometry={nodes.Sphere_cell241.geometry}
        material={materials["Material.001"]}
        position={[-0.583, 0.325, -0.504]}
      />
      <mesh
        name="Sphere_cell242"
        geometry={nodes.Sphere_cell242.geometry}
        material={materials["Material.001"]}
        position={[-0.07, 0.586, -0.728]}
      />
      <mesh
        name="Sphere_cell244"
        geometry={nodes.Sphere_cell244.geometry}
        material={materials["Material.001"]}
        position={[0.817, -0.177, -0.417]}
      />
      <mesh
        name="Sphere_cell245"
        geometry={nodes.Sphere_cell245.geometry}
        material={materials["Material.001"]}
        position={[0.383, 0.41, -0.736]}
      />
      <mesh
        name="Sphere_cell246"
        geometry={nodes.Sphere_cell246.geometry}
        material={materials["Material.001"]}
        position={[-0.375, 0.601, -0.63]}
      />
      <mesh
        name="Sphere_cell247"
        geometry={nodes.Sphere_cell247.geometry}
        material={materials["Material.001"]}
        position={[-0.488, 0.797, -0.329]}
      />
      <mesh
        name="Sphere_cell250"
        geometry={nodes.Sphere_cell250.geometry}
        material={materials["Material.001"]}
        position={[0.344, 0.6, -0.633]}
      />
      <mesh
        name="Sphere_cell251"
        geometry={nodes.Sphere_cell251.geometry}
        material={materials["Material.001"]}
        position={[0.121, -0.28, -0.187]}
      />
      <mesh
        name="Sphere_cell252"
        geometry={nodes.Sphere_cell252.geometry}
        material={materials["Material.001"]}
        position={[-0.485, 0.621, -0.451]}
      />
      <mesh
        name="Sphere_cell254"
        geometry={nodes.Sphere_cell254.geometry}
        material={materials["Material.001"]}
        position={[0.767, -0.624, -0.036]}
      />
      <mesh
        name="Sphere_cell257"
        geometry={nodes.Sphere_cell257.geometry}
        material={materials["Material.001"]}
        position={[-0.484, -0.282, -0.748]}
      />
      <mesh
        name="Sphere_cell259"
        geometry={nodes.Sphere_cell259.geometry}
        material={materials["Material.001"]}
        position={[0.583, -0.548, 0.429]}
      />
      <mesh
        name="Sphere_cell260"
        geometry={nodes.Sphere_cell260.geometry}
        material={materials["Material.001"]}
        position={[0.62, -0.485, 0.589]}
      />
      <mesh
        name="Sphere_cell263"
        geometry={nodes.Sphere_cell263.geometry}
        material={materials["Material.001"]}
        position={[-0.778, 0.183, -0.522]}
      />
      <mesh
        name="Sphere_cell264"
        geometry={nodes.Sphere_cell264.geometry}
        material={materials["Material.001"]}
        position={[-0.606, 0.256, -0.343]}
      />
      <mesh
        name="Sphere_cell265"
        geometry={nodes.Sphere_cell265.geometry}
        material={materials["Material.001"]}
        position={[-0.218, 0.906, 0.295]}
      />
      <mesh
        name="Sphere_cell267"
        geometry={nodes.Sphere_cell267.geometry}
        material={materials["Material.001"]}
        position={[-0.056, -0.653, -0.609]}
      />
      <mesh
        name="Sphere_cell268"
        geometry={nodes.Sphere_cell268.geometry}
        material={materials["Material.001"]}
        position={[0.51, -0.737, 0.324]}
      />
      <mesh
        name="Sphere_cell269"
        geometry={nodes.Sphere_cell269.geometry}
        material={materials["Material.001"]}
        position={[-0.826, -0.434, -0.162]}
      />
      <mesh
        name="Sphere_cell271"
        geometry={nodes.Sphere_cell271.geometry}
        material={materials["Material.001"]}
        position={[-0.243, 0.667, 0.304]}
      />
      <mesh
        name="Sphere_cell272"
        geometry={nodes.Sphere_cell272.geometry}
        material={materials["Material.001"]}
        position={[0.644, 0.471, -0.377]}
      />
      <mesh
        name="Sphere_cell274"
        geometry={nodes.Sphere_cell274.geometry}
        material={materials["Material.001"]}
        position={[-0.722, 0.402, 0.458]}
      />
      <mesh
        name="Sphere_cell275"
        geometry={nodes.Sphere_cell275.geometry}
        material={materials["Material.001"]}
        position={[-0.514, 0.757, 0.128]}
      />
      <mesh
        name="Sphere_cell277"
        geometry={nodes.Sphere_cell277.geometry}
        material={materials["Material.001"]}
        position={[-0.716, 0.1, -0.425]}
      />
      <mesh
        name="Sphere_cell281"
        geometry={nodes.Sphere_cell281.geometry}
        material={materials["Material.001"]}
        position={[-0.929, -0.102, 0.032]}
      />
      <mesh
        name="Sphere_cell282"
        geometry={nodes.Sphere_cell282.geometry}
        material={materials["Material.001"]}
        position={[0.907, -0.238, -0.013]}
      />
      <mesh
        name="Sphere_cell284"
        geometry={nodes.Sphere_cell284.geometry}
        material={materials["Material.001"]}
        position={[-0.144, -0.334, -0.362]}
      />
      <mesh
        name="Sphere_cell285"
        geometry={nodes.Sphere_cell285.geometry}
        material={materials["Material.001"]}
        position={[0.506, 0.2, -0.793]}
      />
      <mesh
        name="Sphere_cell286"
        geometry={nodes.Sphere_cell286.geometry}
        material={materials["Material.001"]}
        position={[0.694, -0.505, 0.141]}
      />
      <mesh
        name="Sphere_cell289"
        geometry={nodes.Sphere_cell289.geometry}
        material={materials["Material.001"]}
        position={[-0.123, 0.48, -0.605]}
      />
      <mesh
        name="Sphere_cell290"
        geometry={nodes.Sphere_cell290.geometry}
        material={materials["Material.001"]}
        position={[-0.232, -0.597, 0.287]}
      />
      <mesh
        name="Sphere_cell291"
        geometry={nodes.Sphere_cell291.geometry}
        material={materials["Material.001"]}
        position={[-0.767, 0.537, -0.172]}
      />
      <mesh
        name="Sphere_cell293"
        geometry={nodes.Sphere_cell293.geometry}
        material={materials["Material.001"]}
        position={[0.937, 0.11, 0.12]}
      />
      <mesh
        name="Sphere_cell294"
        geometry={nodes.Sphere_cell294.geometry}
        material={materials["Material.001"]}
        position={[-0.622, -0.33, 0.503]}
      />
      <mesh
        name="Sphere_cell295"
        geometry={nodes.Sphere_cell295.geometry}
        material={materials["Material.001"]}
        position={[-0.305, -0.566, 0.71]}
      />
      <mesh
        name="Sphere_cell297"
        geometry={nodes.Sphere_cell297.geometry}
        material={materials["Material.001"]}
        position={[0.499, -0.286, 0.722]}
      />
      <mesh
        name="Sphere_cell299"
        geometry={nodes.Sphere_cell299.geometry}
        material={materials["Material.001"]}
        position={[-0.153, -0.77, 0.551]}
      />
      <mesh
        name="Sphere_cell302"
        geometry={nodes.Sphere_cell302.geometry}
        material={materials["Material.001"]}
        position={[-0.235, -0.446, -0.066]}
      />
      <mesh
        name="Sphere_cell304"
        geometry={nodes.Sphere_cell304.geometry}
        material={materials["Material.001"]}
        position={[-0.157, -0.324, 0.686]}
      />
      <mesh
        name="Sphere_cell305"
        geometry={nodes.Sphere_cell305.geometry}
        material={materials["Material.001"]}
        position={[-0.815, 0.271, -0.089]}
      />
      <mesh
        name="Sphere_cell306"
        geometry={nodes.Sphere_cell306.geometry}
        material={materials["Material.001"]}
        position={[-0.794, 0.197, 0.305]}
      />
      <mesh
        name="Sphere_cell307"
        geometry={nodes.Sphere_cell307.geometry}
        material={materials["Material.001"]}
        position={[-0.466, -0.805, 0.178]}
      />
      <mesh
        name="Sphere_cell308"
        geometry={nodes.Sphere_cell308.geometry}
        material={materials["Material.001"]}
        position={[-0.285, -0.56, -0.393]}
      />
      <mesh
        name="Sphere_cell309"
        geometry={nodes.Sphere_cell309.geometry}
        material={materials["Material.001"]}
        position={[-0.876, -0.09, -0.392]}
      />
      <mesh
        name="Sphere_cell310"
        geometry={nodes.Sphere_cell310.geometry}
        material={materials["Material.001"]}
        position={[0.335, -0.567, 0.661]}
      />
      <mesh
        name="Sphere_cell313"
        geometry={nodes.Sphere_cell313.geometry}
        material={materials["Material.001"]}
        position={[-0.694, 0.529, 0.456]}
      />
      <mesh
        name="Sphere_cell314"
        geometry={nodes.Sphere_cell314.geometry}
        material={materials["Material.001"]}
        position={[0.278, 0.922, 0.268]}
      />
      <mesh
        name="Sphere_cell315"
        geometry={nodes.Sphere_cell315.geometry}
        material={materials["Material.001"]}
        position={[0.669, 0.513, 0.509]}
      />
      <mesh
        name="Sphere_cell316"
        geometry={nodes.Sphere_cell316.geometry}
        material={materials["Material.001"]}
        position={[-0.556, -0.004, -0.737]}
      />
      <mesh
        name="Sphere_cell318"
        geometry={nodes.Sphere_cell318.geometry}
        material={materials["Material.001"]}
        position={[-0.468, -0.719, 0.414]}
      />
      <mesh
        name="Sphere_cell321"
        geometry={nodes.Sphere_cell321.geometry}
        material={materials["Material.001"]}
        position={[-0.224, 0.692, -0.394]}
      />
      <mesh
        name="Sphere_cell322"
        geometry={nodes.Sphere_cell322.geometry}
        material={materials["Material.001"]}
        position={[0.555, 0.707, -0.423]}
      />
      <mesh
        name="Sphere_cell325"
        geometry={nodes.Sphere_cell325.geometry}
        material={materials["Material.001"]}
        position={[-0.049, 0.654, -0.363]}
      />
      <mesh
        name="Sphere_cell326"
        geometry={nodes.Sphere_cell326.geometry}
        material={materials["Material.001"]}
        position={[0.341, -0.775, 0.439]}
      />
      <mesh
        name="Sphere_cell327"
        geometry={nodes.Sphere_cell327.geometry}
        material={materials["Material.001"]}
        position={[-0.435, 0.224, 0.731]}
      />
      <mesh
        name="Sphere_cell329"
        geometry={nodes.Sphere_cell329.geometry}
        material={materials["Material.001"]}
        position={[-0.684, 0.118, 0.553]}
      />
      <mesh
        name="Sphere_cell330"
        geometry={nodes.Sphere_cell330.geometry}
        material={materials["Material.001"]}
        position={[-0.257, -0.05, -0.119]}
      />
      <mesh
        name="Sphere_cell331"
        geometry={nodes.Sphere_cell331.geometry}
        material={materials["Material.001"]}
        position={[0.238, 0.821, 0.31]}
      />
      <mesh
        name="Sphere_cell332"
        geometry={nodes.Sphere_cell332.geometry}
        material={materials["Material.001"]}
        position={[-0.2, 0.612, 0.133]}
      />
      <mesh
        name="Sphere_cell333"
        geometry={nodes.Sphere_cell333.geometry}
        material={materials["Material.001"]}
        position={[-0.073, -0.355, 0.907]}
      />
      <mesh
        name="Sphere_cell334"
        geometry={nodes.Sphere_cell334.geometry}
        material={materials["Material.001"]}
        position={[0.394, 0.652, 0.493]}
      />
      <mesh
        name="Sphere_cell335"
        geometry={nodes.Sphere_cell335.geometry}
        material={materials["Material.001"]}
        position={[-0.105, -0.984, 0.068]}
      />
      <mesh
        name="Sphere_cell336"
        geometry={nodes.Sphere_cell336.geometry}
        material={materials["Material.001"]}
        position={[-0.445, -0.876, 0.047]}
      />
      <mesh
        name="Sphere_cell337"
        geometry={nodes.Sphere_cell337.geometry}
        material={materials["Material.001"]}
        position={[0.271, 0.052, 0.138]}
      />
      <mesh
        name="Sphere_cell339"
        geometry={nodes.Sphere_cell339.geometry}
        material={materials["Material.001"]}
        position={[0.135, 0.932, -0.03]}
      />
      <mesh
        name="Sphere_cell341"
        geometry={nodes.Sphere_cell341.geometry}
        material={materials["Material.001"]}
        position={[-0.415, -0.442, 0.226]}
      />
      <mesh
        name="Sphere_cell343"
        geometry={nodes.Sphere_cell343.geometry}
        material={materials["Material.001"]}
        position={[-0.074, 0.32, 0.075]}
      />
      <mesh
        name="Sphere_cell345"
        geometry={nodes.Sphere_cell345.geometry}
        material={materials["Material.001"]}
        position={[-0.357, 0.62, 0.13]}
      />
      <mesh
        name="Sphere_cell347"
        geometry={nodes.Sphere_cell347.geometry}
        material={materials["Material.001"]}
        position={[-0.59, -0.487, -0.613]}
      />
      <mesh
        name="Sphere_cell348"
        geometry={nodes.Sphere_cell348.geometry}
        material={materials["Material.001"]}
        position={[-0.306, -0.017, 0.299]}
      />
      <mesh
        name="Sphere_cell350"
        geometry={nodes.Sphere_cell350.geometry}
        material={materials["Material.001"]}
        position={[0.126, 0.78, 0.387]}
      />
      <mesh
        name="Sphere_cell353"
        geometry={nodes.Sphere_cell353.geometry}
        material={materials["Material.001"]}
        position={[-0.181, -0.873, -0.333]}
      />
      <mesh
        name="Sphere_cell355"
        geometry={nodes.Sphere_cell355.geometry}
        material={materials["Material.001"]}
        position={[-0.912, -0.127, -0.162]}
      />
      <mesh
        name="Sphere_cell356"
        geometry={nodes.Sphere_cell356.geometry}
        material={materials["Material.001"]}
        position={[-0.785, -0.582, 0.075]}
      />
    </group>
  );
}

useGLTF.preload("/Stone/stone.glb");
