/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/ExplodingPlanet/exploding_planet.glb -o src/component/canvas/ExplodingPlanet.jsx -r public -k 
*/

import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import React, { useRef } from "react";
import { useExplode } from "../../hooks/useExplode";

export function ExplodingPlanet(props) {
  const { nodes, materials } = useGLTF("/ExplodingPlanet/exploding_planet.glb");

  const group = useRef(null);
  const { bluebirddistance } = useControls({
    bluebirddistance: {
      value: 2.4,
      min: 0,
      max: 10,
    },
  });
  useExplode(group, {
    distance: bluebirddistance,
    rotationEnabled: true,
  });
  return (
    <group {...props} dispose={null} useRef={group}>
      <mesh
        name="Planet_11_cell007"
        geometry={nodes.Planet_11_cell007.geometry}
        material={materials.Atlas}
        position={[1.927, -1.531, 0.211]}
      />
      <mesh
        name="Planet_11_cell008"
        geometry={nodes.Planet_11_cell008.geometry}
        material={materials.Atlas}
        position={[-0.388, 0.496, 0.902]}
      />
      <mesh
        name="Planet_11_cell024"
        geometry={nodes.Planet_11_cell024.geometry}
        material={materials.Atlas}
        position={[-2.49, -0.647, 0.865]}
      />
      <mesh
        name="Planet_11_cell039"
        geometry={nodes.Planet_11_cell039.geometry}
        material={materials.Atlas}
        position={[1.898, -0.773, 0.565]}
      />
      <mesh
        name="Planet_11_cell047"
        geometry={nodes.Planet_11_cell047.geometry}
        material={materials.Atlas}
        position={[2.098, -0.562, -1.286]}
      />
      <mesh
        name="Planet_11_cell059"
        geometry={nodes.Planet_11_cell059.geometry}
        material={materials.Atlas}
        position={[2.125, -0.611, -0.256]}
      />
      <mesh
        name="Planet_11_cell082"
        geometry={nodes.Planet_11_cell082.geometry}
        material={materials.Atlas}
        position={[0.035, -2.194, 0.638]}
      />
      <mesh
        name="Planet_11_cell083"
        geometry={nodes.Planet_11_cell083.geometry}
        material={materials.Atlas}
        position={[-0.318, 0.671, 2.225]}
      />
      <mesh
        name="Planet_11_cell095"
        geometry={nodes.Planet_11_cell095.geometry}
        material={materials.Atlas}
        position={[-2.096, 0.662, -1.739]}
      />
      <mesh
        name="Planet_11_cell001"
        geometry={nodes.Planet_11_cell001.geometry}
        material={materials.Atlas}
        position={[-1.493, 0.88, 1.089]}
      />
      <mesh
        name="Planet_11_cell002"
        geometry={nodes.Planet_11_cell002.geometry}
        material={materials.Atlas}
        position={[0.688, 0.644, 1.869]}
      />
      <mesh
        name="Planet_11_cell003"
        geometry={nodes.Planet_11_cell003.geometry}
        material={materials.Atlas}
        position={[0.836, 1.37, 1.494]}
      />
      <mesh
        name="Planet_11_cell004"
        geometry={nodes.Planet_11_cell004.geometry}
        material={materials.Atlas}
        position={[0.424, 0.758, 0.147]}
      />
      <mesh
        name="Planet_11_cell006"
        geometry={nodes.Planet_11_cell006.geometry}
        material={materials.Atlas}
        position={[0.81, -0.089, 0.779]}
      />
      <mesh
        name="Planet_11_cell009"
        geometry={nodes.Planet_11_cell009.geometry}
        material={materials.Atlas}
        position={[-0.965, 1.287, 1.572]}
      />
      <mesh
        name="Planet_11_cell011"
        geometry={nodes.Planet_11_cell011.geometry}
        material={materials.Atlas}
        position={[-0.673, -1.541, 0.739]}
      />
      <mesh
        name="Planet_11_cell012"
        geometry={nodes.Planet_11_cell012.geometry}
        material={materials.Atlas}
        position={[-2.314, 0.194, 0.33]}
      />
      <mesh
        name="Planet_11_cell013"
        geometry={nodes.Planet_11_cell013.geometry}
        material={materials.Atlas}
        position={[-1.277, 0.325, 1.608]}
      />
      <mesh
        name="Planet_11_cell014"
        geometry={nodes.Planet_11_cell014.geometry}
        material={materials.Atlas}
        position={[-0.066, -1.073, 1.056]}
      />
      <mesh
        name="Planet_11_cell017"
        geometry={nodes.Planet_11_cell017.geometry}
        material={materials.Atlas}
        position={[-1.763, 1.014, 0.399]}
      />
      <mesh
        name="Planet_11_cell018"
        geometry={nodes.Planet_11_cell018.geometry}
        material={materials.Atlas}
        position={[-1.745, -0.202, 1.039]}
      />
      <mesh
        name="Planet_11_cell019"
        geometry={nodes.Planet_11_cell019.geometry}
        material={materials.Atlas}
        position={[0.182, 0.168, 2.058]}
      />
      <mesh
        name="Planet_11_cell020"
        geometry={nodes.Planet_11_cell020.geometry}
        material={materials.Atlas}
        position={[1.012, 0.001, 1.705]}
      />
      <mesh
        name="Planet_11_cell021"
        geometry={nodes.Planet_11_cell021.geometry}
        material={materials.Atlas}
        position={[-1.696, -0.242, 0.122]}
      />
      <mesh
        name="Planet_11_cell022"
        geometry={nodes.Planet_11_cell022.geometry}
        material={materials.Atlas}
        position={[-0.407, -1.164, 1.062]}
      />
      <mesh
        name="Planet_11_cell023"
        geometry={nodes.Planet_11_cell023.geometry}
        material={materials.Atlas}
        position={[0.923, 0.538, -2.016]}
      />
      <mesh
        name="Planet_11_cell027"
        geometry={nodes.Planet_11_cell027.geometry}
        material={materials.Atlas}
        position={[0.59, -1.097, 0.414]}
      />
      <mesh
        name="Planet_11_cell028"
        geometry={nodes.Planet_11_cell028.geometry}
        material={materials.Atlas}
        position={[-0.251, -0.823, 0.605]}
      />
      <mesh
        name="Planet_11_cell029"
        geometry={nodes.Planet_11_cell029.geometry}
        material={materials.Atlas}
        position={[-0.195, 0.467, 2.626]}
      />
      <mesh
        name="Planet_11_cell030"
        geometry={nodes.Planet_11_cell030.geometry}
        material={materials.Atlas}
        position={[-0.355, 1.019, 2.364]}
      />
      <mesh
        name="Planet_11_cell034"
        geometry={nodes.Planet_11_cell034.geometry}
        material={materials.Atlas}
        position={[0.316, 1.966, -1.9]}
      />
      <mesh
        name="Planet_11_cell040"
        geometry={nodes.Planet_11_cell040.geometry}
        material={materials.Atlas}
        position={[-0.425, -0.626, 2.678]}
      />
      <mesh
        name="Planet_11_cell045"
        geometry={nodes.Planet_11_cell045.geometry}
        material={materials.Atlas}
        position={[1.288, 0.314, -2.299]}
      />
      <mesh
        name="Planet_11_cell046"
        geometry={nodes.Planet_11_cell046.geometry}
        material={materials.Atlas}
        position={[0.645, 0.497, 2.657]}
      />
      <mesh
        name="Planet_11_cell048"
        geometry={nodes.Planet_11_cell048.geometry}
        material={materials.Atlas}
        position={[2.459, -0.547, -0.58]}
      />
      <mesh
        name="Planet_11_cell051"
        geometry={nodes.Planet_11_cell051.geometry}
        material={materials.Atlas}
        position={[1.22, -0.938, 2.319]}
      />
      <mesh
        name="Planet_11_cell053"
        geometry={nodes.Planet_11_cell053.geometry}
        material={materials.Atlas}
        position={[0.662, 0.155, -1.844]}
      />
      <mesh
        name="Planet_11_cell057"
        geometry={nodes.Planet_11_cell057.geometry}
        material={materials.Atlas}
        position={[0.541, -2.117, 1.683]}
      />
      <mesh
        name="Planet_11_cell075"
        geometry={nodes.Planet_11_cell075.geometry}
        material={materials.Atlas}
        position={[1.463, 0.415, 2.352]}
      />
      <mesh
        name="Planet_11_cell076"
        geometry={nodes.Planet_11_cell076.geometry}
        material={materials.Atlas}
        position={[-2.599, -0.118, -0.608]}
      />
      <mesh
        name="Planet_11_cell080"
        geometry={nodes.Planet_11_cell080.geometry}
        material={materials.Atlas}
        position={[-0.809, 0.094, -2.668]}
      />
      <mesh
        name="Planet_11_cell089"
        geometry={nodes.Planet_11_cell089.geometry}
        material={materials.Atlas}
        position={[0.818, 1.106, -2.315]}
      />
      <mesh
        name="Planet_11_cell090"
        geometry={nodes.Planet_11_cell090.geometry}
        material={materials.Atlas}
        position={[-2.012, 1.211, 1.293]}
      />
      <mesh
        name="Planet_11_cell091"
        geometry={nodes.Planet_11_cell091.geometry}
        material={materials.Atlas}
        position={[-0.272, -0.405, -2.776]}
      />
      <mesh
        name="Planet_11_cell096"
        geometry={nodes.Planet_11_cell096.geometry}
        material={materials.Atlas}
        position={[-0.81, 1.903, -1.763]}
      />
      <mesh
        name="Planet_11_cell103"
        geometry={nodes.Planet_11_cell103.geometry}
        material={materials.Atlas}
        position={[-0.845, -0.974, 2.395]}
      />
      <mesh
        name="Planet_11_cell104"
        geometry={nodes.Planet_11_cell104.geometry}
        material={materials.Atlas}
        position={[-2.176, -0.26, -0.45]}
      />
      <mesh
        name="Planet_11_cell106"
        geometry={nodes.Planet_11_cell106.geometry}
        material={materials.Atlas}
        position={[1.514, -1.501, -1.335]}
      />
      <mesh
        name="Planet_11_cell112"
        geometry={nodes.Planet_11_cell112.geometry}
        material={materials.Atlas}
        position={[0.695, 0.339, -0.052]}
      />
      <mesh
        name="Planet_11_cell119"
        geometry={nodes.Planet_11_cell119.geometry}
        material={materials.Atlas}
        position={[-0.444, 1.191, -1.053]}
      />
      <mesh
        name="Planet_11_cell128"
        geometry={nodes.Planet_11_cell128.geometry}
        material={materials.Atlas}
        position={[-1.904, 1.916, 0.295]}
      />
      <mesh
        name="Planet_11_cell129"
        geometry={nodes.Planet_11_cell129.geometry}
        material={materials.Atlas}
        position={[2.185, -1.139, -1.134]}
      />
      <mesh
        name="Planet_11_cell130"
        geometry={nodes.Planet_11_cell130.geometry}
        material={materials.Atlas}
        position={[-2.442, -0.684, -0.85]}
      />
      <mesh
        name="Planet_11_cell135"
        geometry={nodes.Planet_11_cell135.geometry}
        material={materials.Atlas}
        position={[0.652, 2.17, 1.639]}
      />
      <mesh
        name="Planet_11_cell031"
        geometry={nodes.Planet_11_cell031.geometry}
        material={materials.Atlas}
        position={[-1.879, -0.431, 0.966]}
      />
      <mesh
        name="Planet_11_cell033"
        geometry={nodes.Planet_11_cell033.geometry}
        material={materials.Atlas}
        position={[-1.206, 1.393, 1.533]}
      />
      <mesh
        name="Planet_11_cell035"
        geometry={nodes.Planet_11_cell035.geometry}
        material={materials.Atlas}
        position={[-1.495, 0.927, -0.962]}
      />
      <mesh
        name="Planet_11_cell036"
        geometry={nodes.Planet_11_cell036.geometry}
        material={materials.Atlas}
        position={[-0.427, 2.369, -0.144]}
      />
      <mesh
        name="Planet_11_cell037"
        geometry={nodes.Planet_11_cell037.geometry}
        material={materials.Atlas}
        position={[1.378, 0.348, -1.006]}
      />
      <mesh
        name="Planet_11_cell038"
        geometry={nodes.Planet_11_cell038.geometry}
        material={materials.Atlas}
        position={[-0.303, 0.101, -2.833]}
      />
      <mesh
        name="Planet_11_cell041"
        geometry={nodes.Planet_11_cell041.geometry}
        material={materials.Atlas}
        position={[-1.499, 1.605, -1.722]}
      />
      <mesh
        name="Planet_11_cell042"
        geometry={nodes.Planet_11_cell042.geometry}
        material={materials.Atlas}
        position={[-1.816, 0.666, 0.527]}
      />
      <mesh
        name="Planet_11_cell050"
        geometry={nodes.Planet_11_cell050.geometry}
        material={materials.Atlas}
        position={[1.236, -0.437, -0.169]}
      />
      <mesh
        name="Planet_11_cell052"
        geometry={nodes.Planet_11_cell052.geometry}
        material={materials.Atlas}
        position={[-0.79, 1.823, 0.462]}
      />
      <mesh
        name="Planet_11_cell054"
        geometry={nodes.Planet_11_cell054.geometry}
        material={materials.Atlas}
        position={[-2.382, -0.107, 0.557]}
      />
      <mesh
        name="Planet_11_cell056"
        geometry={nodes.Planet_11_cell056.geometry}
        material={materials.Atlas}
        position={[-0.202, 1.461, -1.931]}
      />
      <mesh
        name="Planet_11_cell060"
        geometry={nodes.Planet_11_cell060.geometry}
        material={materials.Atlas}
        position={[-0.86, 0.797, 0.202]}
      />
      <mesh
        name="Planet_11_cell061"
        geometry={nodes.Planet_11_cell061.geometry}
        material={materials.Atlas}
        position={[-1.646, -1.016, -0.088]}
      />
      <mesh
        name="origin"
        geometry={nodes.origin.geometry}
        material={materials.Atlas}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/ExplodingPlanet/exploding_planet.glb");
