name: Deploy to S3 and Invalidate CloudFront

on:
  push:
    branches:
      - master # master 브랜치에서 push 발생 시 실행

jobs:
  deploy:
    runs-on: ubuntu-22.04 # 안정적인 Ubuntu 22.04로 고정

    steps:
      # 1. 저장소 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. AWS Credentials 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ fromJson(secrets.aws_cloudfront_cicd_secrets).AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ fromJson(secrets.aws_cloudfront_cicd_secrets).AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ fromJson(secrets.aws_cloudfront_cicd_secrets).AWS_DEFAULT_REGION }}

      # 3. 종속성 설치 및 브라우저리스트 업데이트
      - name: Install dependencies and update browserslist
        run: |
          yarn install
          npx update-browserslist-db@latest --force

      # 4. 빌드 (CI 환경에서 경고 무시)
      - name: Build project
        run: |
          CI=false yarn build

      # 5. S3로 배포
      - name: Deploy to S3
        run: |
          aws s3 sync ./build s3://www.yourd.xyz.mainhompage --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ fromJson(secrets.aws_cloudfront_cicd_secrets).AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ fromJson(secrets.aws_cloudfront_cicd_secrets).AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ fromJson(secrets.aws_cloudfront_cicd_secrets).AWS_DEFAULT_REGION }}

      # 6. CloudFront 캐시 무효화
      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E1DFXQ25304IKX --paths "/*"
        env:
          AWS_ACCESS_KEY_ID: ${{ fromJson(secrets.aws_cloudfront_cicd_secrets).AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ fromJson(secrets.aws_cloudfront_cicd_secrets).AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ fromJson(secrets.aws_cloudfront_cicd_secrets).AWS_DEFAULT_REGION }}